### ISSUE TITLE
.ex & .exs highlighting 

### ISSUE THREAD

**Issue by JackyChiu** [arcticicestudio/nord-vim#102]
I recently started using this colour scheme (it's beautiful) and I noticed for Elixir's script files `.exs` extension, no highlighting is being applied. The same highlighting rules from `.ex` elixir files should be applied to `.exs` files. 

<img width="920" alt="screen shot 2018-02-19 at 2 54 21 pm" src="https://user-images.githubusercontent.com/11095732/36395041-098f18a2-1585-11e8-8c4f-dcc8c246ebf9.png">

`.exs` (left) and `.ex` (right)

I could try to help out but I'm not familiar with how the syntax highlighting works 😅

**Comment by JackyChiu** [comment]
Also the README says details about language support are in the wiki but it doesn't seem to be accessible

**Comment by arcticicestudio** [comment]
This is related to plugin support. After a quick look over the officially supported Vim syntax files it seems like there is no support for Elixir out-of-the-box, but there are plugins like e.g. [elixir-editors/vim-elixir][p] which explicitly add support for file extensions:

> Filetype detection for `.ex`, .`exs` and `.eex` files

[p]: https://github.com/elixir-editors/vim-elixir

**Comment by arcticicestudio** [comment]
@JackyChiu Can you please test if the theme works when using the plugin mentioned above? I've checked their syntax highlighting code and normally it should work out-of-the-box.

**Comment by JackyChiu** [comment]
Hey! I did have that plugin, and for some reason the filetype wasn't getting recognized when loading `.exs` files. I guess it started happening the same time I started using Nord, deosn't seem to be a issue on this end, sorry!
