### ISSUE TITLE
Bad coloring for haskell syntax

### ISSUE THREAD

**Issue by vabatta** [arcticicestudio/nord-vim#104]
Hi, I started using the haskell syntax theme available at `https://github.com/neovimhaskell/haskell-vim` and in conjunction with this theme the colors of all the keywords are of the same color. Any fix?

**Comment by arcticicestudio** [comment]
Hi @vabatta :wave: 
Thanks for your contribution :+1: 

It's more a feature than a "fix" since the plugin uses specific syntax color groups that need to be implemented for the theme. I've submitted #150 that adds support for the plugin to improve the highlighting for Haskell.
