### ISSUE TITLE
Underline in search highlight

### ISSUE THREAD

**Issue by hejersbo** [arcticicestudio/nord-vim#105]
I recently started using the nord-vim colorscheme and so far I am very pleased. Great job. I have a question though regarding search highlight. When search highlight is enabled the searched item is both hightlighted and underlined. Is it possible to disable the underlining? See screenshot below.

![image](https://user-images.githubusercontent.com/7511328/36969096-cf1950e4-2064-11e8-94ff-e337df8811de.png)

**Comment by arcticicestudio** [comment]
The underline style has been added in #41 to improve the currently selected search result when there are multiple search results, otherwise only the cursor indicates the current search result item position. More detailed are posted in the linked PR.

It might be a good idea to make the underline effect configurable to also prevent incompatibility problems with plugins that modify the styling of search results.

**Comment by hejersbo** [comment]
Thanks for the answer. I will consider submitting a PR.

**Comment by arcticicestudio** [comment]
@hejersbo
Sorry for the delay, I've had no free time (job :man_health_worker:, study :book:, life :weight_lifting_man: etc.) to work on my or any other :octocat: OSS project (see Tweets :bird: from [April][t-april] and [June][t-june]), but from the beginning of July I finished my studies and can [finally spend time on OSS again][t-back] :green_heart:

Like @dylnmc already mentioned a option to only disable underlines for the `IncSearch` is too specific and can simply be achieved with the custom scoped overrides. To [disable underlines globally a new configuration has been implemented][conf-us] which has been shipped with [release version 0.9.0][v0.9.0].

[t-april]: https://twitter.com/arcticicestudio/status/987753414342914049
[t-june]: https://twitter.com/arcticicestudio/status/1004777280646844417
[t-back]: https://twitter.com/arcticicestudio/status/1010013091793256448
[conf-us]: https://github.com/arcticicestudio/nord-vim#underline-support
[v0.9.0]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.9.0
