### ISSUE TITLE
Lighter column number

### ISSUE THREAD

**Issue by huyvohcmc** [arcticicestudio/nord-vim#110]
The color of column number is very dark it nearly looks the same with the background. Adding a little bit brightness to it will be better, no? In other color schemes, the column number is very easy to be recognized with.

<img width="180" alt="screen shot 2018-03-13 at 9 45 27 pm" src="https://user-images.githubusercontent.com/17645203/37348996-01913e16-2708-11e8-9b72-7af16a4278d9.png">

**Comment by dylnmc** [comment]
If you don't want to see cursorline:

in vimrc:

```vim
augroup NordMods
    autocmd!
    autocmd ColorScheme nord highlight CursorLineNr ctermfg=6 guifg=#81A1C1
    autocmd ColorScheme nord highlight CursorLine ctermbg=NONE guibg=#2E3440
augroup end

set cursorline
```

result:
![i](https://user-images.githubusercontent.com/7635158/37411202-a551190c-2778-11e8-9afc-29f2e48c01f8.png)

If you *do* want to see cursoline, then remove the autocmd that sets cursorline above.

Cheers

**Comment by huyvohcmc** [comment]
Thank you
