### ISSUE TITLE
Vim doesn't apply true color with this theme

### ISSUE THREAD

**Issue by huyvohcmc** [arcticicestudio/nord-vim#111]
If I enable italics, my comment background will change to the dark color just exactly like [this issue](https://github.com/arcticicestudio/nord-vim/issues/82).

But if I disable italics, whenever I source my config file it will automatically highlight the last search result (weird). I believe these two issues have something to do with the true color of the terminal.

One more thing is that Vim highlighting for `.vimrc` is very different to Neovim highlighting for `.vimrc` even tho Vim and Nvim use the same config.

Using vim:
<img width="1497" alt="screen shot 2018-03-14 at 11 48 47 pm" src="https://user-images.githubusercontent.com/17645203/37417241-57077e02-27e2-11e8-97fc-13d95950d6d9.png">
Using nvim:
<img width="1497" alt="screen shot 2018-03-14 at 11 48 18 pm" src="https://user-images.githubusercontent.com/17645203/37417226-4ee35cb4-27e2-11e8-8ddd-271383630641.png">

You can notice that the brightness of the comment text is also much darker in Vim than in Neovim even tho they have the same brightness level (set to 20).
Note that all those things only happen in Vim, on Neovim they work just fine.

O.S: MacOS High Sierra
Vim: 8.0
Neovim: 0.2.2
Terminal: iterm2 build 3.1.5
The configuration can be found at https://github.com/huyvohcmc/dotfiles/blob/master/init.vim

**Comment by arcticicestudio** [comment]
Can you please try to move the `set termguicolors` line after the `colorscheme nord` line? Otherwise the scheme is loaded before Vim knows that it should use true colors.

**Comment by huyvohcmc** [comment]
I've put the termguicolors after the colorscheme, no luck.

**Comment by dylnmc** [comment]
For some reason the way that it is currently set up, when termguicolors is enabled, it doesn't set comments to italic .. but only in vim.

I have found that if you put `let g:nord_italic = 1` before setting colorscheme to `nord` then it fixes that problem. (I am not particularly fond of how g:nord_italic` works, but it works.)

Also, regarding the bold font that appears only in neovim: it appears your neovim is picking up on the `gui=` variable which is set to `bold` in gvim for things like `hi Statement`, but not for terminal vim. There is some inconsistency there ... bold for gui and none for term.

**Comment by huyvohcmc** [comment]
I still have the problem. The brightness of the comments are too dark and when I source the file I can't see the comments anymore.

Can you provide me some methods to debug this one? It really annoys me since I want to switch from nvim to vim and I love this theme but it can't work like the way it is on nvim..

**Comment by dylnmc** [comment]
I tried to get `autocmd SourceCmd` to work with a `nohlsearch` at the end, but I couldn't.

I would say that to make things easier, you can use this, which I use all the time (to mostly clear hlsearch but also to refresh a diff and refresh syntax ... I got a little carried away, but the point is that a `nohlsearch` is added as extra functionality to `<c-l>`):
```vim
" <c-l> is a bit more useful (nohl && diffu && <c-l> && refresh syntax from start)
nnoremap <silent> <c-l> :nohlsearch<bar>diffupdate<bar>execute "normal! \<lt>c-l>"<bar>syntax sync fromstart<cr>
```

I *also* have the following in my vimrc:

```vim
nnoremap <silent> <leader>v :edit $MYVIMRC<bar>call feedkeys("\<c-l>")<cr>
nnoremap <silent> <leader>V :source $MYVIMRC<bar>call feedkeys("\<c-l>")<cr>
nnoremap <silent> <leader>S :source %<bar>call feedkeys("\<c-l>")<cr>
```

Like I said unfortunately, I couldn't get it to work with the autocmd..

**Comment by huyvohcmc** [comment]
`brew install vim -with-override-system-vim` and `map <silent> <leader><cr> :let @/=""<cr>` solved the problem. TIA!

**Comment by arcticicestudio** [comment]
@huyvohcmc Good to hear the problem has been solved. As far as I understand the problem was a outdated version of Vim which doesn't even supported true colors right? Just want to know for my notes, otherwise this solution can help other users facing the same problem.
