### ISSUE TITLE
Terminal.app character covered by cursor is invisible

### ISSUE THREAD

**Issue by laxman20** [arcticicestudio/nord-vim#113]
Using terminal.app on OS X with the nord theme and vim with the nord color scheme. The character under the cursor cannot be seen. It works correctly in iTerm2 though.

![screen shot 2018-03-23 at 5 36 30 pm](https://user-images.githubusercontent.com/1408115/37854377-0c378e36-2ec1-11e8-9f0c-94aa32d5c343.png)

**Comment by laxman20** [comment]
I'll create the issue in the terminal.app repository because it's not vim specific.

**Comment by dylnmc** [comment]
@laxman20 

https://github.com/altercation/solarized/issues/82#issuecomment-317255798

Just change the cursor color in the settings. For example, you can reduce the opacity, as I linked above.

Cheers

**Comment by dylnmc** [comment]
Same issue here: https://github.com/altercation/solarized/issues/82#issuecomment-317255798

Maybe use a different terminal (like iTerm2 :eyes:)
