### ISSUE TITLE
Compatibility with indentLine

### ISSUE THREAD

**Issue by dlee** [arcticicestudio/nord-vim#115]
Hi, it would be great if nord-vim was compatible with [indentLine](https://github.com/Yggdroot/indentLine).

Right now, using indentLine, it looks like this:
<img width="360" alt="screen shot 2018-04-03 at 5 45 09 pm" src="https://user-images.githubusercontent.com/7035/38282778-c9acb880-3766-11e8-8cb8-b96db50e9223.png">

I'm currently using this as a workaround:
```vimscript
hi Conceal guifg=#3B4252 guibg=NONE ctermbg=NONE
```

To make it look like this:
<img width="361" alt="screen shot 2018-04-03 at 5 44 56 pm" src="https://user-images.githubusercontent.com/7035/38282803-e5af0600-3766-11e8-82b6-40f27272dc62.png">

**Comment by arcticicestudio** [comment]
The colors of the indent line can be [customized with configurations of the plugin][c]. For example to use `nord1` as foreground color add the following to your config:

```vim
let g:indentLine_color_term = 0
let g:indentLine_bgcolor_term = "NONE"
let g:indentLine_color_gui = '#3b4252'
let g:indentLine_bgcolor_gui = 'NONE'
```

![gh-115-plugin-config-preview](https://user-images.githubusercontent.com/7836623/38294592-a05f1d4e-37eb-11e8-9cfa-9a09e3c6c1f2.png)

If your using a cursor line background color you can also add `let g:indentLine_concealcursor = 0` to hide the indent lines for the current cursor line. 

[c]: https://github.com/Yggdroot/indentLine#customization
