### ISSUE TITLE
Issue with tmuxline color and vim-airline

### ISSUE THREAD

**Issue by khoadcao** [arcticicestudio/nord-vim#117]
When using `tmuxline.vim` with `nord-vim` in `vim-airline`, I get this issue everytime I start `tmux`:

`/<my home directory>/.tmux-status.conf:18: bad colour: NONE`

After some search around the repo, I found this issue https://github.com/arcticicestudio/nord-vim/issues/11, which is exactly the same as mine, but was already fixed for `lightline.vim`.

Could this fix be also implemented for `vim-airline`? Thank you!

**Comment by arcticicestudio** [comment]
@khoadcao  Thanks for your contribution :+1: 

Sorry for the delay, I've had no free time (job :man_health_worker:, study :book:, life :weight_lifting_man: etc.) to work on my or any other :octocat: OSS project (see Tweets :bird: from [April][t-april] and [June][t-june]), but from the beginning of July I finished my studies and can [finally spend time on OSS again][t-back] :green_heart:

I've implemented the changes from #11 for airline by replacing the used `nord4` color with `nord5`.
Can you please check out the [`improvement/gh-117-airline-tmuxline-compatibility`](https://github.com/arcticicestudio/nord-vim/tree/improvement/gh-117-airline-tmuxline-compatibility) branch and test if this fixes the error? It works fine on my system, the airline theme is automatically applied and works fine when running `:Tmuxline airline` too.

[t-april]: https://twitter.com/arcticicestudio/status/987753414342914049
[t-june]: https://twitter.com/arcticicestudio/status/1004777280646844417
[t-back]: https://twitter.com/arcticicestudio/status/1010013091793256448

**Comment by khoadcao** [comment]
@arcticicestudio After some testing, it seems that the patch has fixed the problem. Thank you!

Closing it now.

**Comment by arcticicestudio** [comment]
@khoadcao Thanks for your feedback :+1: 

I reopened this issue because it'll be closed via automation when the corresponding PR is merged :smile:

**Comment by arcticicestudio** [comment]
:rocket: Deployed in release version 🏷 [0.10.0](https://github.com/arcticicestudio/nord-vim/releases/tag/v0.10.0)
