### ISSUE TITLE
StorageClass color may not be displaying

### ISSUE THREAD

**Issue by chaucerbao** [arcticicestudio/nord-vim#123]
I think the color for **StorageClass** may not be displaying. In this JavaScript example, `const` should be highlighted, if I am [reading this correctly](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L250), but it doesn't seem to be showing.

![image](https://user-images.githubusercontent.com/794434/41370835-89d30394-6efd-11e8-9d35-b98d345eab72.png)
Nord vs OneDark (MacOS Terminal.app, same [syntax file](https://github.com/pangloss/vim-javascript/blob/master/syntax/javascript.vim#L34))

I'm using [Nord Terminal.app Theme](https://github.com/arcticicestudio/nord-terminal-app)

![image](https://user-images.githubusercontent.com/794434/41371470-46466cd6-6eff-11e8-91ba-ed98d8c8b396.png)

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

I've not been able to reproduce the problem. The `const` keyword is highlighted correctly using

* the default builtin JavaScript syntax (uses the `javaScriptReserved` group)
![gh-123-reproduction-default-syntax](https://user-images.githubusercontent.com/7836623/41496992-b0759498-714c-11e8-815d-9744a31b5594.png)
* the supported syntax plugin [pangloss/vim-javascript][]
![gh-123-reproduction-plugin-pangloss-vim-javascript](https://user-images.githubusercontent.com/7836623/41496995-b9b51c54-714c-11e8-8784-fe13de59a7a6.png)
* the syntax plugin [mxw/vim-jsx][]
![gh-123-reproduction-plugin-mxw-vim-jsx](https://user-images.githubusercontent.com/7836623/41496999-bbef9198-714c-11e8-8350-2a031bfb6b84.png)

Can you please verify that the plugin is installed and loaded correctly? Also make sure that there are no syntax errors which might break the highlighting.

[pangloss/vim-javascript]: https://github.com/pangloss/vim-javascript
[mxw/vim-jsx]: https://github.com/mxw/vim-jsx

**Comment by chaucerbao** [comment]
Ah, my apologies. I just realized that the file I was viewing was a TypeScript file. I'll have to take a look over [there](https://github.com/leafgarland/typescript-vim/blob/master/syntax/typescript.vim#L109).

I checked a JavaScript file and you're right, it highlights correctly.

**Comment by chaucerbao** [comment]
It looks like they [categorize it as an Identifier](https://github.com/leafgarland/typescript-vim/blob/master/syntax/typescript.vim#L263), and [Identifiers in nord-vim](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L238) have no color assignment.
