### ISSUE TITLE
Add Vim 8 terminal highlighting

### ISSUE THREAD

**Issue by cg433n** [arcticicestudio/nord-vim#125]
Vim 8 comes with a built-in terminal (`:terminal`). The default terminal colors don't look quite right.
<img width="221" alt="screen shot 2018-06-19 at 8 03 19 am" src="https://user-images.githubusercontent.com/868735/41605902-4bbc1bc4-7397-11e8-8dee-7f87b65f0a12.png">

**Comment by arcticicestudio** [comment]
:rocket: Deployed in release version 🏷 [0.10.0](https://github.com/arcticicestudio/nord-vim/releases/tag/v0.10.0)
