### ISSUE TITLE
Underline and spell checking

### ISSUE THREAD

**Issue by diegoholiveira** [arcticicestudio/nord-vim#129]
Hi guys. I'm using nord for a while and recently I work with a lot of specifications, so I start using a lot the vim spell checker and I notice something: the default configuration of vim + nord doesn't change the spell checker underline, like you can see here:

![screen shot 2018-06-25 at 17 28 12](https://user-images.githubusercontent.com/93187/41874108-4ae62a2c-789d-11e8-9ef3-b4cfbc71c07b.png)

Then, I add this into my vimrc:

```
highlight clear SpellBad
highlight clear SpellCap
highlight clear SpellLocal
highlight clear SpellRare

highlight SpellBad cterm=underline
highlight SpellCap cterm=underline
highlight SpellLocal cterm=underline
highlight SpellRare cterm=underline
```

And now the underline is as I expected:

![screen shot 2018-06-25 at 17 29 08](https://user-images.githubusercontent.com/93187/41874151-687f474e-789d-11e8-877c-b00ccd8084e5.png)

My question is: why the underline of spell checking is not setup by the plugin? Or this it's not under the purpose of the plugin? Or, there is a better way? 

Thanks a lot for this awesome color scheme, I use it everywhere.

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

The recently released [version 0.9.0][v0.9.0] added a new [configuration to allow users to globally toggle underlines][config-readme]. The theme config `g:nord_underline` variable must be added to your `~/.vimrc` file and set to `1` to enable underlines.
The yellow and red colors indicate different types of spell problems. If you like to use it without any colors (like shown on your second screenshot) you can simply use scoped overrides to customize a color scheme for your preferences, e.g. to change the color of the `Spell*` groups **only** for the _Nord_ theme by adding this snippet to your `~/.vimrc` file:

```vim
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight SpellBad cterm=underline
  autocmd ColorScheme nord highlight SpellCap cterm=underline
  autocmd ColorScheme nord highlight SpellLocal cterm=underline
  autocmd ColorScheme nord highlight SpellRare cterm=underline
augroup end
```

You can name the group (`nord-overrides`) to whatever you want.

[v0.9.0]: https://github.com/arcticicestudio/nord-vim/releases/tag/v0.9.0
[config-readme]: https://github.com/arcticicestudio/nord-vim#underline-support

**Comment by diegoholiveira** [comment]
> The theme config g:nord_underline variable must be added to your ~/.vimrc file and set to 1 to enable underlines.

Bot screenshots attached here is with this setting enabled.

The snipped suggested keeps my spell errors as red and yellow.

**Comment by diegoholiveira** [comment]
So, I finally take a look into the pallet and understand better the issue. The red and yellow are both part of the palled (I assume it was not part of the pallet and it was vim defaults).

So, I made a little change in `nord.vim` locally and I think I may be better than the current one:

![screen shot 2018-06-26 at 11 17 07](https://user-images.githubusercontent.com/93187/41918309-7b99974a-7932-11e8-9fa7-928aefe64172.png)


The changes are locally, but if you agree on it, I can open a PR. The diff is here:

```
-call s:hi("SpellBad", s:nord11_gui, s:nord0_gui, s:nord11_term, "NONE", "undercurl", s:nord11_gui)
-call s:hi("SpellCap", s:nord13_gui, s:nord0_gui, s:nord13_term, "NONE", "undercurl", s:nord13_gui)
+call s:hi("SpellBad", s:nord7_gui, s:nord0_gui, s:nord11_term, "NONE", "undercurl", s:nord11_gui)
+call s:hi("SpellCap", s:nord9_gui, s:nord0_gui, s:nord13_term, "NONE", "undercurl", s:nord13_gui)
```

I change from the Aurora to Frost colors.

What do you think about it?

**Comment by arcticicestudio** [comment]
Thanks for your suggestions, but the yellow and red colors are by design. Both groups `SpellBad` and `SpellCap` are highlighting errors. Nord uses `nord11` and `nord13` for errors and warnings while `nord9` and `nord7` are used for other elements like syntax keywords and classes/types. If both are used for spell problems you won't be able to distinguish them from correct code because they'll mix up with the code colors.
If you want to colorize spell problems as shown on the screenshot you can use your posted changes by adding them to the override group.
