### ISSUE TITLE
Italic support

### ISSUE THREAD

**Issue by kepbod** [arcticicestudio/nord-vim#13]
Is there any plan to support Italic?

**Comment by arcticicestudio** [comment]
Can you explain what exactly should be supported?

I try to limit the syntax highlighting to colors for port projects that do not support font attributes by default. Vim and all other terminal based projects in general are affected by this cause there can be still be problems when I'd set the `italic` attribute for groups and the terminal is not able to handle it.

Besides that there are not many elements that I'd like to use italic fonts for. I only use it for static methods/functions in OOP languages that provide this mechanism.

**Comment by kepbod** [comment]
Just like described [here](https://github.com/rakr/vim-one#italic-support). Supporting italic is just an advice, and I think this colorscheme is cool enough now. Thanks for developing such great colorscheme.

**Comment by arcticicestudio** [comment]
I'll try to implement a global variable to enable/disable italics when I'm back home next weekend. I think the implementation ifself isn't at all, but the fact that Nord tries to avoid italics :smile: 

Currently I see no use for italic styled fonts except for some really special cases. Maybe it could be used for the `Special` group or if the language syntax highlighting is advanced enough to differ between normal and static functions/methods like I described for IntelliJ Idea above.

Some themes like to use italic fonts for comments, but in my option this makes it even harder to read :worried:
Comments should be colorized in a decent, not disturbing color to keep the focus on the code.

Please feel free to tell me which parts of the theme you'd like to see using italics, maybe we can introduce another option for it like e.g. "Use italic font for comments" or something like this.

**Comment by kepbod** [comment]
I agree to most of what you said. Thanks so much for supporting this feature. Most theme used italics for comments, so I think using italic font for comments is enough. 😄
