### ISSUE TITLE
Syntax highlighting doesn't work in Asciidoc

### ISSUE THREAD

**Issue by tidux** [arcticicestudio/nord-vim#131]
Even simple things like header layers don't work at all.  The highlight rules are set up here: https://github.com/asciidoc/vim-asciidoc

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 

The theme currently supports some groups of the official default syntax bundled with Vim, but you're referring to a third-party plugin which groups must be implemented for the theme to be available.

**Comment by tidux** [comment]
Actually it looks like it's bundled with the standard Vim distribution as part of Vim 8 now.

```
# dpkg -S /usr/share/vim/vim80/syntax/asciidoc.vim
vim-runtime: /usr/share/vim/vim80/syntax/asciidoc.vim
```

**Comment by tidux** [comment]
I can confirm it's an upstream part of Vim >=8.0 on Linux and OS X, and by extension on WSL/Win10.

**Comment by arcticicestudio** [comment]
Thanks for your patience @tidux

I've been too busy with my "real" life and the development of the [official Nord website][n] to work on the massive amount of issues/PRs that were submitted each day for all of Nord's port projects.

I've submitted #152 that adss basic syntax highlighting support for Asciidoc. It will be merged into the next release version.

<p align="center"><img src="https://user-images.githubusercontent.com/7836623/56083880-1165ce00-5e2b-11e9-9389-f21435942464.png" /></p>

[n]: https://www.nordtheme.com
