### ISSUE TITLE
Remove VertSplit's background

### ISSUE THREAD

**Issue by huyvohcmc** [arcticicestudio/nord-vim#132]
Can we make the background of VertSplit to be the same color of the window's background? I don't see any reason why we should make the VertSplit looks bold and thick, it actually takes a lot of space in small laptops when you splitting more than 2 windows.

**Comment by viniarck** [comment]
+1. 

I also overwrote it with `autocmd ColorScheme nord hi VertSplit guibg=#2E3440 guifg=#434C5E`

**Comment by arcticicestudio** [comment]
Hi @huyvohcmc and @viniarck  :wave: 
Thanks for your contributions :+1: 

I've been too busy with my "real" life and the development of the [official Nord website][n] to work on the massive amount of issues/PRs that were submitted each day for all of Nord's port projects.

I've submitted #153 that changes the style of the vertical split line and also adds a new theme config to allow users to use the legacy style. It will be merged into the next release version.


<p align="center"><strong>With base editor background (default)</strong><img src="https://user-images.githubusercontent.com/7836623/56088648-8e259600-5e85-11e9-8a6f-2c03d26eff4b.png" /></p>

```viml
let g:nord_bold_vertical_split_line = 1
```

<p align="center"><strong>With enabled bold <code>nord1</code> background</strong><img src="https://user-images.githubusercontent.com/7836623/56088647-8e259600-5e85-11e9-8be5-d86232ca8278.png" /></p>

[n]: https://www.nordtheme.com

**Comment by viniarck** [comment]
Thanks @arcticicestudio. Appreciated that!
