### ISSUE TITLE
When watching diff's with vimagit or fugitive it's bugged

### ISSUE THREAD

**Issue by sebastianks** [arcticicestudio/nord-vim#136]
Hello

I am using nord-vim with Hyper terminal (also nord themed), and everything is great - I love it! But I just started using `vimagit` (tried `fugitive` too) and when watching diff's the highlight is green/red and so is the text, so can't actually see what's changed.

Can someone help me fix this is the core or maybe a hotfix at my machine, since the theme is unusable together with those 2 plugins.

Here's a screenshot of the actual deal:
![](https://i.imgur.com/CZmK7O0.png)

**Comment by tomgeorge** [comment]
+ 1, I am also having color issues when doing diffs.

`nvim -d fruits1.md fruits2.md`
![vim-d](https://user-images.githubusercontent.com/1291508/51116106-c27aaf00-17cf-11e9-8c86-fb35889fb4e4.png)

This is a fugitive window:
![fugitive](https://user-images.githubusercontent.com/1291508/51116125-d58d7f00-17cf-11e9-885b-7fb6a2c3fac1.png)

my `.vimrc` is at https://github.com/tomgeorge/dotfiles

**Comment by arcticicestudio** [comment]
Hi @sebastianks  and @tomgeorge :wave:
Thanks for your patience, I've been too busy with my "real" life and the development of the [official Nord website][n] to work on the massive amount of issues/PRs that were submitted each day for all of Nord's port projects.

[n]: https://www.nordtheme.com

**Comment by sebastianks** [comment]
@arcticicestudio I think mine was due to not using Nord in Hyper as I thought I did. There's no issue for me when using Hyper+Nord and Vim+Nord.

**Comment by arcticicestudio** [comment]
@tomgeorge If the solution I suggested above doesn't work please open a new issue. This way it makes it easier for me to keep track of all the currently open issues.
