### ISSUE TITLE
Yellow generator expressions in CMake

### ISSUE THREAD

**Issue by markand** [arcticicestudio/nord-vim#137]
Hello,

In CMakeLists.txt, generator expressions are shown with a yellow background. I think this is not much readable and should be changed.

![image](https://user-images.githubusercontent.com/11919008/47014861-ba1cc480-d14b-11e8-93b6-1a3a228f6c38.png)

Having the cursor on the line is also hard to read:

![image](https://user-images.githubusercontent.com/11919008/47014907-de78a100-d14b-11e8-9e43-78149bb5e379.png)

This has been tested with latest version from Git, using `termguicolors` setting in terminal vim.

**Comment by arcticicestudio** [comment]
Hi @markand :wave: 
Thanks for your contribution :+1: 

I've submitted #151 that improves the highlighting for CMake generator expression.
