### ISSUE TITLE
Add better support for Rust Language

### ISSUE THREAD

**Issue by TerminalWitchcraft** [arcticicestudio/nord-vim#138]
The colorscheme is awesome and works flawlessly. However, writing Rust code doesn't seem too pleasant. It would be great if [Rust](https://www.rust-lang.org/en-US/) is supported. Below, I have attached a screenshot of how Rust looks like today using Nord
![2018-10-19-185246_3840x2160_scrot](https://user-images.githubusercontent.com/17204042/47220736-40493d00-d3d0-11e8-9cbf-64a0503dd6fe.png)

**Comment by arcticicestudio** [comment]
Hi @TerminalWitchcraft :wave: 
Thanks for your contributions :+1: 

I've been too busy with my "real" life and the development of the [official Nord website][n] to work on the massive amount of issues/PRs that were submitted each day for all of Nord's port projects.

I've submitted #154 that adds basic syntax highlighting support for Rust. It will be merged into the next release version.

[n]: https://www.nordtheme.com
