### ISSUE TITLE
Current argument in function signature preview of jedi-vim not properly highlighted

### ISSUE THREAD

**Issue by mkalinski** [arcticicestudio/nord-vim#14]
[Jedi-vim](https://github.com/davidhalter/jedi-vim) is a popular Vim plugin for python programming.

One of its features is a live preview of the signature of the function that is being currently typed. Current position in the argument list is highlighted, but in nord-vim this is not visible. That's because jedi-vim assumes that `TabLine` and `CursorLine` groups are highlighted differently, but they aren't in nord-vim.

From https://github.com/davidhalter/jedi-vim/blob/master/after/syntax/python.vim:

```viml
    if exists('g:colors_name')
        hi def link jediFunction CursorLine
        hi def link jediFat TabLine
    else
        hi jediFunction term=NONE cterm=NONE ctermfg=6 guifg=Black gui=NONE ctermbg=0 guibg=Grey
        hi jediFat term=bold,underline cterm=bold,underline gui=bold,underline ctermbg=0 guibg=#555555
    endif
```

Either `TabLine` and `CursorLine` should be highlighted differently, or the plugin-specific `jediFunction` and `jediFat` overridden (`jediFat` is the one that should stand out more).

**Comment by arcticicestudio** [comment]
I'll test it next weekend, but as far as I've seen your suggestion with overriding the methods sounds like a clean solution. Changing the `TabLine` or `CursorLine` would break many other plugins that rely on this groups.

**Comment by arcticicestudio** [comment]
I've tested the auto completion feature today and for me the list looks fine.
The currently selected entry has a lighter background and the font using the main accent theme color `nord8`.

![ghi-14-scrot-auto-completion](https://cloud.githubusercontent.com/assets/7836623/22403424/e8feef2a-e616-11e6-959c-537dd9ff7b1d.png)

Can you please post a screenshot of your view, your `.vimrc` config and maybe some example code so I can try to reproduce it.

And by the way, this plugin is awesome! 😄 
I'll definitely use it for my Python projects, thanks :+1:

**Comment by mkalinski** [comment]
Yeah, this display is alright, I meant something different. I'll provide the screenshots.

Here is the function call signature prompt in the default theme:
![jedi-default](https://cloud.githubusercontent.com/assets/959502/22416645/2f809642-e6d0-11e6-855c-ec49d15e5f1e.png)

Meanwhile in nord:
![jedi-nord](https://cloud.githubusercontent.com/assets/959502/22416659/45b9e184-e6d0-11e6-88a2-2204583773a0.png)

**Comment by arcticicestudio** [comment]
Thanks, this looks definitely worng 😆 
I'll fix it as soon as I've got some freetime for it 😄

**Comment by arcticicestudio** [comment]
Implemented optimized styles for the `jediFunction` and `jediFat` groups.

<p align="center"><strong>Before</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/22618347/4857d88e-eada-11e6-9696-83a8886f5771.png"/><br><strong>After</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/22618354/63ddffde-eada-11e6-8a60-52a39642728e.png"/></p>
