### ISSUE TITLE
Doesn't Seem to Install Correctly 

### ISSUE THREAD

**Issue by robotdna** [arcticicestudio/nord-vim#148]
I have installed Nord through my .Xresources for urxvt as per the documentation- I copied and pasted it in, and rebuilt the .Xresources file. I then installed nord-vim through Vundle, and enabled it, and my coloring looks completely wrong. Here is a side-by-side screenshot, left hand side with the Jellybeans syntax highlighting, and right hand side with nord-vim: 
![nord](https://user-images.githubusercontent.com/22781288/55846761-1e6d7f00-5b04-11e9-990d-27d2ecbac9ba.png)

Any idea what's going on here? In it's current state it is unusable on my system.

**Comment by robotdna** [comment]
Just for clarity- I am using the transparent background setting in vim for Jellybeans, which is why it appears to be more Nord-like with the background color on the left than the right.

**Comment by robotdna** [comment]
Update: I am able to get the background to go from green to the gray it should be by setting :set background=dark ONLY while inside a vim session, and it doesn't do anything either set before or after the nord colorscheme call in the .vimrc.

**Comment by arcticicestudio** [comment]
Hi @robotdna 👋 
Can you please try to reproduce the problem using a clean (default) Vim config file? You can do this by using the `-u` flag followed by the path to the config file, e.g. `vim -u /tmp/test-config.vim`. 
Also please check if your `$TERM` environment variable is set to the correct terminal type: `echo $TERM`. it should output something like `xterm-256color` to ensure it uses a 256-bit compatible terminal.
Afterwards set Nord as colorscheme and see if the problem still occurs.

In most cases such reported problems are related to system or Vim setup problems. There might be a config that overrides Nord's theme definitions or your terminal doesn't use the necessary configs. Other themes might not have the problem because they are either not using the `dark` theme style or only define 16-bit or true color (256-bit) colors.

**Comment by robotdna** [comment]
@arcticicestudio The `-u` flag was giving me some issues so I just commented everything out besides the default Vundle vimrc and some Powerline settings which shouldn't do anything:
`let g:powerline_pycmd="py3"` and `let laststatus=2`

Now I am getting an error when trying to use vim at all, and can't use vim anymore:

`Error detected while processing function <SNR>13_CSApprox[46]..<SNR>13_CSApproxImpl[38]..<SNR>13_FixupGuiInfo:
line    1:
E716: Key not present in Dictionary: 0
Error detected while processing /home/duncan/Sync/personal/dotfiles/.vim/after/plugin/CSApprox.vim:
line   28:
E171: Missing :endif
Press ENTER or type command to continue`

I am not really sure what I need to do next. I did check my `$TERM` in my terminal and it returns `bash: rxvt-unicode-256color: command not found, which seems to be correct.

**Comment by robotdna** [comment]
Update- by moving the CSApprox.vim file out of my .vim/after/plugin/ folder, I can edit files like a stock vim config. The only issue is that as soon as I call `:colorscheme nord` it throws this:

`Error detected while processing function <SNR>10_CSApprox[46]..<SNR>10_CSApproxImpl[38]..<SNR>10_FixupGuiInfo:
line    1:
E716: Key not present in Dictionary: 0
Press ENTER or type command to continue
`

Which is part of what I was getting before. I'm somewhat lost here, and don't really understand why I'm getting these errors as my understanding was that the CSApprox stuff was for GUI vim, which I am not using.

**Comment by arcticicestudio** [comment]
The errors will come from the fact that Vundle is still active and it tries to auto-load plugins or internal code. Using a clean config allows us to ensure we can chase down the problem by ensuring only the Nord color scheme is the only "external" (non Vim) code that gets loaded. Please also completely uncomment Vundle all other plugins like Powerline. Afterwards manually download the Nord theme file...

```sh
mkdir -p ~/.vim/colors
curl -o ~/.vim/colors/nord.vim https://raw.githubusercontent.com/arcticicestudio/nord-vim/develop/colors/nord.vim
```

...and load it by adding the following lines to your (now clean) config:

```viml
colorscheme nord
```

Also, I remember there where some issues with `rxvt` based terminals. Are you using `rxvt-unicode` or the original one?

**Comment by robotdna** [comment]
> The errors will come from the fact that Vundle is still active and it tries to auto-load plugins or internal code. Using a clean config allows us to ensure we can chase down the problem by ensuring only the Nord color scheme is the only "external" (non Vim) code that gets loaded. Please also completely uncomment Vundle all other plugins like Powerline. Afterwards manually download the Nord theme file...
> 
> ```shell
> mkdir -p ~/.vim/colors
> curl -o ~/.vim/colors/nord.vim https://raw.githubusercontent.com/arcticicestudio/nord-vim/develop/colors/nord.vim
> ```
> 
> ...and load it by adding the following lines to your (now clean) config:
> 
> ```viml
> colorscheme nord
> ```
> 
> Also, I remember there where some issues with `rxvt` based terminals. Are you using `rxvt-unicode` or the original one?

Alright, so I actually just wiped everything with CSApprox references out of my .vim/ directory. I then cleaned my .vimrc, and started over, adding everything again. I am using rxvt-unicode, not the original rxvt. After removing all the CSApprox folders and files I now have a functioning Nord colorscheme running through Vundle. Thank you for your fantastic help!

**Comment by arcticicestudio** [comment]
No problems, nice to see its working now 🚀
