### ISSUE TITLE
add support for vim-startify

### ISSUE THREAD

**Issue by ScrumpyJack** [arcticicestudio/nord-vim#159]
could you add highligting support for vim-startify?

https://github.com/mhinz/vim-startify/blob/master/syntax/startify.vim

**Comment by arcticicestudio** [comment]
Hi @ScrumpyJack :wave:, thanks for your contribution :+1:
Sorry for the delay, unfortunately my free time to work on Nord is limited.

I've implemented support for the plugin in #176. It'll be merged and deployed with the next release version [0.13.0][v].

 [v]: https://github.com/arcticicestudio/nord-vim/projects/19
