### ISSUE TITLE
nord_uniform_status_lines does not work with airline

### ISSUE THREAD

**Issue by astier** [arcticicestudio/nord-vim#168]
The setting `nord_uniform_status_lines` does not work with airline. The statusline does change its colors.

**Comment by arcticicestudio** [comment]
Hi @astier :wave:, thanks for your contribution :+1:
@jmurinello submitted PR #169 that implements the missing support for the theme configuration. I've reviewed and merged it already so it'll be deployed with the next release version [0.13.0][].

[0.13.0]: https://github.com/arcticicestudio/nord-vim/projects/19
