### ISSUE TITLE
Underlined cursor line number in gutter

### ISSUE THREAD

**Issue by alexandremjacques** [arcticicestudio/nord-vim#174]
Hi,

I'm using Nord theme for VIM 8 on iTerm2 (also using Nord theme) and recently (my guess is after the last major iTerm2 update) I noticed that my line number gutter started appearing underlined on highlight.

![Screen Shot 2019-09-29 at 21 22 45](https://user-images.githubusercontent.com/1953298/65842131-c0c22e80-e2ff-11e9-88d1-abfe9c05c008.png)

Any ideas how to resolve? I mean, remove the underline from the line number.

Regards.

**Comment by arcticicestudio** [comment]
Hi @alexandremjacques :wave:, thanks for your contribution :+1:
Maybe this is also related to https://github.com/arcticicestudio/nord-iterm2/issues/9. I'll try to reproduce this when updating to the latest _iTerm2_ version.

**Comment by nixtrace** [comment]
This might be related to latest Vim defaulting to underline for `CursorLineNr`:
https://github.com/vim/vim/blob/017ba07fa2cdc578245618717229444fd50c470d/src/highlight.c#L256

**Comment by arcticicestudio** [comment]
@nixtrace Really nice catch :tada: 
[Comparing with the parent commit][c] shows that `underline` attribute was explicitly set for `cterm`.
The question is if this was done on purpose or should be reported as bug.
If this is a change that'll stay in Vim itself I'll update _Nord Vim_ to explicitly [disable the `cterm` attribute for the `CursorLineNr` group][g].

I haven't updated to the latest _iTerm2_ version yet (only running macOS at my job), but I guess this is superfluous now anyway. I'll also see if this is reproducible on my personal system (_Arch Linux_) using the latest Vim version.

[c]: https://github.com/vim/vim/compare/d9b0d83b13d2691e4544709abd87eac004715175...017ba07fa2cdc578245618717229444fd50c470d#diff-80fffb3e9c20e93e5b2328a9a20e19c9
[g]: https://github.com/arcticicestudio/nord-vim/blob/a77972696328dc6405bdf2348203110d97e95d19/colors/nord.vim#L221-L225

**Comment by nixtrace** [comment]
:+1: I can see the underline on Arch and Ubuntu running Vim `version 8.1.2105`. Thanks!
