### ISSUE TITLE
can't install with vundle

### ISSUE THREAD

**Issue by vanniuner** [arcticicestudio/nord-vim#190]
Plugin 'arcticicestudio/nord-vim' install fail
I clone the git project and copy nord.vim to ~/.vim/colors
and use colorschema nord 
but it does not work

some error output :
`488: Trailing characters:   <div class=
line 3747:
E488: Trailing characters:   <div class=
line 3748:
E488: Trailing characters:   </div>
line 3749:
E488: Trailing characters: </div>
line 3751:
E488: Trailing characters:   <div aria-live=
line 3753:
E488: Trailing characters:   </body>
line 3754:
E488: Trailing characters: </html>
Press ENTER or type command to continue
`

**Comment by arcticicestudio** [comment]
Hi @vanniuner, I've never used _Vundle_, but regarding to their [Quick Start Guide][qs] it works similar to [vim-plug][vp]. Have you made sure the _Vundle_ plugin (`git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim`) is installed correctly?

Also could you please try to to reproduce the problem with a minimal `vimrc` to ensure there problem is not related to any other plugin or configuration:

```viml
" Set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" It is required to let Vundle manage itself. 
Plugin 'VundleVim/Vundle.vim'
Plugin 'arcticicestudio/nord-vim'
call vundle#end()

syntax enable
colorscheme nord
```

[qs]: https://github.com/VundleVim/Vundle.vim#quick-start
[vp]: https://github.com/junegunn/vim-plug

**Comment by vanniuner** [comment]
.it seems a network erro.sorry ,waste your time
