### ISSUE TITLE
.diff files not supported

### ISSUE THREAD

**Issue by aschult5** [arcticicestudio/nord-vim#191]
I believe the following are missing:

- DiffAdd
- DiffChange
- DiffDelete
- DiffText

**Comment by arcticicestudio** [comment]
Hi @aschult5 :wave:, thanks for your contribution :+1:

Actually the listed groups are [already supported by Nord][b].
Have you tried to change the `.diff` file extension to `.patch`? This is the more common file extension (somehow related to the history of *nix systems and the development of the Linux kernel) and it's also supported by the Vim syntax highlighting definitions.

Also please make sure you're running the [latest release version][rl] of Nord.

[b]: https://github.com/arcticicestudio/nord-vim/blame/2212c21a510b93210747a33aef095a2ae10b87ad/colors/nord.vim#L382-L396
[rl]: https://github.com/arcticicestudio/nord-vim/releases/latest

**Comment by aschult5** [comment]
Hi @arcticicestudio,

There must have been something wrong with my vim configuration, as it is working now.
Sorry for the false report and thanks for this great colorscheme!

**Comment by arcticicestudio** [comment]
No problem, nice that it works for you now :smile:
