### ISSUE TITLE
Nord colorscheme isn't working in Vim. Itaclic comments not working either. 

### ISSUE THREAD

**Issue by bradagy** [arcticicestudio/nord-vim#192]
I recently downloaded the nord colorscheme using vim-plug and I have `colorscheme nord` in my vimrc. The font has changed but I can't seem to get the exact "nordish" look like you all have in the documentation. The background stays black and does not change to gray like you folks have in your documentation. Please help if possible.

Here is my .vimrc file: [vimrc](https://github.com/bradagy/dotfiles/blob/master/.vimrc)

Here is a picture of my background after I've added `colorscheme nord` to my vimrc: https://imgur.com/Z92MwZa

OS: Ubuntu 18.04
Terminal: bash

**Comment by arcticicestudio** [comment]
Hi @bradagy, could you please…

1. …try to reproduce the problem using a minimal _Vim_ configuration (clean `vimrc`), e.g. this one (using _vimplug_ as plugin manager):
  ```viml
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

" Works with both enabled and disabled italic font option.
let g:nord_italic = 1

syntax enable
colorscheme nord
  ```
2. …make sure you're running the [latest plugin version][rll].
3. …make sure you've installed the plugin after adding it to your `vimrc` by running `:PlugInstall`.
4. …try to reproduce the problem when disabling [Nord's italic font rendering option][dfi].
5. …make sure you're aware of the [requirements and tricky „hacks” when it comes to font rendering][dffr] in terminals and _Vim_.
6. …try if other themes working fine (builtin or another theme plugin like e.g. _solarized_).

[dfi]: https://www.nordtheme.com/docs/ports/vim/configuration#italic-style
[dffr]: https://www.nordtheme.com/docs/ports/vim/configuration#font-rendering
[rll]: https://github.com/arcticicestudio/nord-vim/releases/latest

**Comment by bradagy** [comment]
> Hi @bradagy, could you please…
> 
> 1. …try to reproduce the problem using a minimal _Vim_ configuration (clean `vimrc`), e.g. this one (using _vimplug_ as plugin manager):
> 
> ```viml
> call plug#begin(expand('~/.vim/plugged'))
> Plug 'arcticicestudio/nord-vim'
> call plug#end()
> 
> " Works with both enabled and disabled italic font option.
> let g:nord_italic = 1
> 
> syntax enable
> colorscheme nord
> ```
> 
> 1. …make sure you're running the [latest plugin version](https://github.com/arcticicestudio/nord-vim/releases/latest).
> 2. …make sure you've installed the plugin after adding it to your `vimrc` by running `:PlugInstall`.
> 3. …try to reproduce the problem when disabling [Nord's italic font rendering option](https://www.nordtheme.com/docs/ports/vim/configuration#italic-style).
> 4. …make sure you're aware of the [requirements and tricky „hacks” when it comes to font rendering](https://www.nordtheme.com/docs/ports/vim/configuration#font-rendering) in terminals and _Vim_.
> 5. …try if other themes working fine (builtin or another theme plugin like e.g. _solarized_).

Fixed it. Thank you.

**Comment by arcticicestudio** [comment]
Nice to see it works for you now :+1: 
Could you please shortly describe the solution so maybe other users with the same problem can apply it when findings this issue :smile:
