### ISSUE TITLE
airline: Could not resolve airline theme "nord".

### ISSUE THREAD

**Issue by powelleric** [arcticicestudio/nord-vim#193]
Since upgrading my plugins, I am getting this error: airline: Could not resolve airline theme "nord". 

Also, if I do `:AirlineTheme nord`, I get `airline: There is an error in theme "nord"`.

**Comment by arcticicestudio** [comment]
Hi @powelleric, could you please…

1. …try to reproduce the problem using a minimal _Vim_ configuration (clean `vimrc`), e.g. this one (using _vimplug_ as plugin manager):
  ```viml
call plug#begin(expand('~/.vim/plugged'))
Plug 'vim-airline/vim-airline'
Plug 'arcticicestudio/nord-vim'
call plug#end()

syntax enable
colorscheme nord
  ```
2. …make sure you're running the [latest plugin version][rll].
3. …make sure you've installed the plugin after adding it to your `vimrc` by running `:PlugInstall`.
4. …try if other _airline_ themes working fine (builtin or another theme plugin).

[rll]: https://github.com/arcticicestudio/nord-vim/releases/latest

**Comment by powelleric** [comment]
Thank you for the minimal config.  That showed the issue to be in my config.  I found that `Plug 'flazz/vim-colorschemes'` was the issue.  Removing that seems to have fixed the issue.

Thanks for your help and for the wonderful theme :)

**Comment by arcticicestudio** [comment]
You're welcome, great to see it works for you now :+1:
