### ISSUE TITLE
go function names not colored

### ISSUE THREAD

**Issue by rumpl** [arcticicestudio/nord-vim#206]
Hi, thank you for this awesome theme!

I can't get it to have the same output as the one from the website, mainly the function names are not colored:
<img width="514" alt="Screen Shot 2020-05-11 at 3 06 04 PM" src="https://user-images.githubusercontent.com/99933/81565102-1af89700-9399-11ea-8c31-67e80daddc8d.png">

I'm using Neovim (v0.4.3) and iTerm2 (with Nord theme and true color enabled), I have `set termguicolors` in my config file. What else can I do?

Thanks

**Comment by arcticicestudio** [comment]
Hi @rumpl, looks like this is the same problem like reported and resolved in #203. Could you please try the [suggestions I've posted there][r]?

[r]: https://github.com/arcticicestudio/nord-vim/issues/203#issuecomment-620800009

**Comment by rumpl** [comment]
@arcticicestudio that was exactly the problem! I'm so sorry I opened the issue, I did search the issues though... :(

Cheers!

**Comment by arcticicestudio** [comment]
No problem, nice to see it works for you now 😄
