### ISSUE TITLE
display abnormal

### ISSUE THREAD

**Issue by yangxyo** [arcticicestudio/nord-vim#210]
I'm from solarized. But something seems wrong.

![image](https://user-images.githubusercontent.com/32320149/85947595-4dc51180-b97e-11ea-922e-55483fb4fcd5.png)
![image](https://user-images.githubusercontent.com/32320149/85947667-b4e2c600-b97e-11ea-9d33-183e851f0fa7.png)
![image](https://user-images.githubusercontent.com/32320149/85947841-ab0d9280-b97f-11ea-9498-6202dd60fdb2.png)

```
Plug 'arcticicestudio/nord-vim'
Plug 'edkolev/tmuxline.vim'
Plug 'vim-airline/vim-airline'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
```

I feel it maybe the problem of fonts. So I try `source code pro powerline`,`Meslo LG for powerline`, and so on. it does not work. How can I fix it?

```
$ vim --V
VIM - Vi IMproved 8.2

$ echo $TERM
xterm-256color

:echo &encoding
utf8
```

![image](https://user-images.githubusercontent.com/32320149/85948264-80710900-b982-11ea-8a37-4210c1f24a3d.png)

Howerver, with the app of MacVim, it's okay. I don't meet this question with solarized

**Comment by yangxyo** [comment]
https://github.com/vim-airline/vim-airline/issues/2162#issuecomment-650771646

**Comment by arcticicestudio** [comment]
Nice to see it works for you now and thanks for the link to the solution 👍 
I've added a [note in the backlog][b] to ensure this solution will be included in the project documentation and FAQs.

[b]: https://github.com/arcticicestudio/nord-vim/projects/1#card-40981741
