### ISSUE TITLE
Scheme editing for usage with Go(lang)

### ISSUE THREAD

**Issue by kaynetik** [arcticicestudio/nord-vim#214]
_Disclosure:_ In case I didn't fully follow the community standard for submitting a new issue, please point me in the right direction as to how it should be done. Since this is more of a help inquiry than an actual issue.

The only thing I was wondering is how could I alter `nord-vim` so it's more like in the GoLand. I'm mostly interested in the following:
* If param to a function is an *interface* or another function, make it *bold* and/or of *slightly* different color
* Return types of a function to be a *slightly* different color

Since a picture says a thousand words...

In the `SS No.1` I would like that the `RegistrationReaderFn` is of slightly different color and that `session.UserInfo` is bolded.
![SS No.1](https://i.imgur.com/EJp3nnA.png)

In the `SS No.2` I would like that `handlers.Handler` is of slightly different color and that both interfaces are bolded in params.
![SS No.2](https://i.imgur.com/XkiG3ZP.png)

I would welcome any suggestions as to how I would achieve this. I'm aware that such information is probably waiting behind the corner, but since I recently transitioned to nvim I'm still not very versed at finding such minor tweaks.

**Comment by kaynetik** [comment]
_FIY_
I've followed the recommended settings from the relevant docs, to achieve what I wanted. But to no avail. Related settings in my rc file are:
```
let g:nord_cursor_line_number_background = 1
let g:nord_bold = 1
let g:nord_italic = 1
let g:nord_italic_comments = 1
let g:nord_underline = 1
colorscheme nord
```

**Comment by arcticicestudio** [comment]
Hi @kaynetik :wave:
Until the [GitHub “Discussions“][gh-disc] feature is not GA using issues are the only GitHub-like way to ask for support, but you could also use on of [Nord's project communities][com].
The problem you're facing is that Vim doesn't come with rich syntax highlighting support for Go by default so you need to extend it using a plugin like [vim-go][][fatih/vim-go] (written in Vim script, exists longer and provides great features) or [govim][govim/govim] (written mainly in Go, newer with focus on compatibility with _gopls_).

Could you please try to follow the instructions I've posted in https://github.com/arcticicestudio/nord-vim/issues/203#issuecomment-620800009?

[com]: https://www.nordtheme.com/community
[fatih/vim-go]: https://github.com/fatih/vim-go
[gh-disc]: https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions
[govim/govim]: https://github.com/govim/govim

**Comment by kaynetik** [comment]
@arcticicestudio Thanks a lot for the quick and helpful response.
I will surely give it a go (pun intended) 🤣 

Initially, I was using `vim-go`, but I've switched to `coc.nvim => coc-go`. But both seem to be having similar issues. I have nothing to lose in trying another one. Anyhow, I'm not dropping NORD no matter what.
