### ISSUE TITLE
Possible conflicting file names for lightline theme

### ISSUE THREAD

**Issue by yhu266** [arcticicestudio/nord-vim#215]
itchyny/lightline.vim#488

As we tested, removing the file `autoload/lightline/colorscheme/nord.vim` in `nord-vim` solves this issue.

**Comment by yhu266** [comment]
This issue occurs when the user choose a colorscheme other than `nord`, but still want to use `nord` as the lightline theme.

**Comment by arcticicestudio** [comment]
Hi @yhu266 :wave:, thanks for your contribution :+1:

This topic has been discussed some weeks ago and I posted my opinion about it in https://github.com/arcticicestudio/nord-vim/pull/178#issuecomment-638881528.
It's the same like for the bundled _airline_ theme: When plugins like _lightline_ provide some kind of API to allow others to create themes for their plugin, they should not bundle these custom themes but only some default or own ones.

Like I've also said in the linked comment above I wouldn't have contributed the theme to the _lightline.vim_ repository if I had known that this would cause loading problems. My assumption was that the loading logic is “clever enough“ to not try to load plugins twice or even fail when trying to.
Removing the bundled themes from this repository is not a option so maybe we need to change the way the _airline_ and _lightline_ themes are loaded. I'd need to research how Vim handles the special `autoload` directory, but maybe there's a way to move the themes into another directory and only load them when a specific variable like e.g. `g:nord_lightline_support` is set to `1`.

Anyway, the changes in #216 are trivial and I should work fine to fix the problem, but I guess we need to think about ways to improve the current integration.
