### ISSUE TITLE
Python: uses of Special

### ISSUE THREAD

**Issue by mkalinski** [arcticicestudio/nord-vim#22]
Since you decided not to highlight the blanket `Special` group, these probably need to be addressed.

There are two groups defined in Python syntax that use `Special` by default: `pythonEscape` and `pythonDoctest`.

`pythonEscape` should probably be using `SpecialChar`, since it's for `\n` and friends. `pythonDoctest` refers to the `>>>` (and `...`) that start doctests in python docstrings. Perhaps also `SpecialChar`, or `SpecialComment`?

**Comment by arcticicestudio** [comment]
Implemented optimized styles for the `pythonEscape` group.
![ghi-22-scrot-pythonescape](https://cloud.githubusercontent.com/assets/7836623/22618370/ad74e7fc-eada-11e6-89f2-23b351e8aa2b.png)

The `pythonDoctest` group actually works the way it should. It uses the same colors like outside of the doctests section, e.g. numbers are using `pythonNumber`, the `for` keyword uses `pythonRepeat` or the `in range` builtin uses `pythonBuiltin`.
If I link the `pythonDoctest` group to e.g. `SpecialComment` everything will be colorized with `nord8` and you won't be able to distinguish the code elements.
