### ISSUE TITLE
SQL: uses of Special

### ISSUE THREAD

**Issue by mkalinski** [arcticicestudio/nord-vim#23]
Now this one uses it to a ridiculous degree.

Two groups are linked to `Special`: `sqlSpecial` (which consists just of `true`, `false` and `null`) and the very blanket `sqlKeyword`, which groups every reserved word that does not start a statement (ie. not `select`, `insert` and friends), is not an operator or a type/function name.

This is defined in `sqloracle.vim` syntax file, which is the one loaded by default if no other sql dialect is explicitly selected.

**Comment by arcticicestudio** [comment]
The `sqlSpecial` group is now linked to `sqlKeyword` to colorize constants like `true`/`false` and `null` as keywords.
