### ISSUE TITLE
Cannot find color scheme 'nord'

### ISSUE THREAD

**Issue by ain** [arcticicestudio/nord-vim#236]
## Steps to reproduce

1. Follow [3 points in installation instructions](https://github.com/arcticicestudio/nord-vim#quick-start)
2. Restart Vim

## What happens

```
$ vim
Error detected while processing /Users/ain/.vimrc:
line   73:
E185: Cannot find color scheme 'nord'
```

ln 73 is 
```
colorscheme nord 
```

`nord-vim` is installed:

<img width="127" alt="nord-vim" src="https://user-images.githubusercontent.com/370576/101405181-03a26d80-38d8-11eb-82e6-0bcf71bf39b7.png">

## What should happen

As per installation guideline, no error should appear.

## Additional details

Vim specs:

```
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec  2 2020 22:03:27)
macOS version
Included patches: 1-1719
Compiled by MacPorts
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       -tcl
-autoservername    +folding           +multi_byte        +termguicolors
-balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
-browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              -perl              +title
-clientserver      +job               +persistent_undo   -toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python            +visual
+conceal           +linebreak         -python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
-cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       -lua               -ruby              +wildmenu
+dialog_con        +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
-dnd               +mouse             -sound             -xfontset
-ebcdic            -mouseshape        +spell             -xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/clang -c -I. -Iproto -DHAVE_CONFIG_H   -I/opt/local/include -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -DMACOS_X -DMACOS_X_DARWIN  -pipe -Os -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch x86_64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: /usr/bin/clang   -L/opt/local/lib -Wl,-headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -arch x86_64 -o vim        -lm  -lncurses -liconv -lintl -framework AppKit    -L/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -lintl -framework CoreFoundation -L/opt/local/Library/Frameworks/Py /opt/local/Library/Frameworks/Python.framework/Versions/2.7/Python       
```

**Comment by arcticicestudio** [comment]
Hi @ain 👋🏼 

I've guess your [.vim][r] repository is what is used for Vim so I quickly checked the `vimrc` file. It looks like you've placed the `colorscheme` statement before _vim-plug_‘s plugin loading block. Therefore Vim can't find the theme because it is not yet available in the global scope.
Can you please try to move the `colorscheme` [below the block of _vim-plug_ block][ref]?

The Nord Vim documentation about [theme configurations][dco] and [customizations][dca] already has a information box at the top that tries to notify the user to take the order to statements in the `vimrc` file into account, but I guess its a good idea to add these to the [activation][di#a] section and README in the repository too.

[r]: https://github.com/ain/.vim/blob/master/.vimrc
[dco]: https://www.nordtheme.com/docs/ports/vim/configuration 
[dca]: https://www.nordtheme.com/docs/ports/vim/customization
[di#a]: https://www.nordtheme.com/docs/ports/vim/installation#activation
[ref]: https://github.com/ain/.vim/blob/fb29db/.vimrc#L72

**Comment by ain** [comment]
Thanks for such a prompt feedback @arcticicestudio ! 

I did in fact follow the guidance and the best result I was able to get was this:

<img width="1440" alt="Screenshot 2020-12-08 at 10 56 39" src="https://user-images.githubusercontent.com/370576/101471566-c37ad380-3947-11eb-8716-16d1475c48dd.png">

**Comment by ain** [comment]
Necessary to add that I'm running Vim in `tmux`:

```
$ tmux -V
tmux 3.1c
```

**Comment by arcticicestudio** [comment]
It looks like you're missing the actual terminal emulator color theme. The information box at the top of the [installation documentation][i] provides some details, but in short this means you need to install/activate the [Nord port][p] for whatever terminal emulator you're running, e.g. _iTerm2_/_Terminal.app_ on macOS, _Tilix_/_GNOME Terminal_ on Linux or _PuTTY_/_MinTTY_ on Windows.

[i]: https://www.nordtheme.com/docs/ports/vim/installation
[p]: https://www.nordtheme.com/ports

**Comment by ain** [comment]
Excellent! That was indeed the case, installing [Nord.terminal](https://github.com/arcticicestudio/nord-terminal-app) profile for _Terminal.app_ and restarting it solved the issue! 

Thanks again for the support!

<img width="1280" alt="Screenshot 2020-12-08 at 21 40 15" src="https://user-images.githubusercontent.com/370576/101539092-429af680-399e-11eb-97eb-6104efdc05fb.png">

**Comment by arcticicestudio** [comment]
Great to see it works for you now 🎉 
By the way, the ⍰ signs in the bar and some UI elements are caused by font rendering issues. You can install a so called “patched“ font that is especially compiled for terminals. One of the most popular project is [NerdFonts][nf] which provides patched fonts for almost any well-known font family.

[nf]: https://github.com/ryanoasis/nerd-fonts
