### ISSUE TITLE
Multiple languages: uses of Identifier

### ISSUE THREAD

**Issue by mkalinski** [arcticicestudio/nord-vim#24]
So I finally found out how the `Identifier` group seems to be usually used in vim syntax files. It's rather obvious, really. For languages like `bash`, `tcl`, `perl`, `php`, etc. `Identifier` is used for sigil-prefixed forms like `$var`.

Since there are many languages that use sigils like these, I'd once again recommend that the group `Identifier` should be unconditionally highlighted. I don't think you ever stated what you intended to do with `Identifier` in #12.

**Comment by arcticicestudio** [comment]
The `Identifier` group is used for the name of variables / attributes which are used to "identifiy" those.
All variables / attributes are colorized with `nord4` which is defined in the Nord Style Guide and implemented in all port projects this way.
