### ISSUE TITLE
Add Nord Hyper to Terminal List

### ISSUE THREAD

**Issue by ryanponce** [arcticicestudio/nord-vim#25]
There is a [Nord theme](https://github.com/pddstudio/hyper-nord) for [Hyper](https://hyper.is/). I think this should be added to the list of terminal themes.

**Comment by arcticicestudio** [comment]
Hi, thanks for your notice!
❄️ ⚡️ [Nord Hyper](https://www.npmjs.com/package/nord-hyper) version 🏷  [0.1.0](https://github.com/arcticicestudio/nord-hyper/releases/tag/v0.1.0) has been released as [official port project](https://github.com/arcticicestudio/nord#port-projects).
