### ISSUE TITLE
NonText won't change colors

### ISSUE THREAD

**Issue by hrqmonteiro** [arcticicestudio/nord-vim#251]
Hi, why, no matter what i put in the `NonText` highlight sections, the tilde symbols remains the same color? (nord1 color, or #3b4252)?

I am trying to make it don't appear, that is, setting it to the bg color (nord0gui, or #2E3440), but no matter which color i put (be it the fg or the bg), it remains EXACTLY the same, like this:

![2021-02-24_00-11](https://user-images.githubusercontent.com/17055027/108941974-d773ce80-7634-11eb-94ab-e0b47e83ce4e.png)

Even if i put a crazy color on purpose, like this:

![2021-02-24_00-11_1](https://user-images.githubusercontent.com/17055027/108942013-efe3e900-7634-11eb-99d6-0c993d7c0a26.png)

It simply doesn't change...

**Comment by hrqmonteiro** [comment]
Well, zero help, i give up.

**Comment by arcticicestudio** [comment]
Hi @hrqmonteiro, please note that this is OSS and people spending their free time to work on projects while users get everything for free. So expecting respond times like a payed support service is a mindset that many should change.

Anyway, you can override the highlight group using a custom `aurgroup` like described in [the customization documentation for Nord Vim][3]. This is an example that uses `nord11` as foreground for end of buffer markers:

```vim
augroup nord-theme-overrides
  autocmd!
  " Vim version <8.0.0
  autocmd ColorScheme nord highlight NonText ctermfg=1 guifg=#BF616A
  " Vim version >=8.0.0
  autocmd ColorScheme nord highlight EndOfBuffer ctermfg=1 guifg=#BF616A
augroup END
```

For Vim versions `>=8.0.0` the `EndOfBuffer` group can be used which is scoped to these markers while versions `<8.0.0` must use `NonText` which targets multiple elements (including end of buffer markers).
Note that the builtin help from Vim is also always a great source for information, e.g. check out [`:help EndOfBufffer`][2] and [`:help NonText`][1] for more details about both groups.

[1]: https://vimhelp.org/syntax.txt.html#hl-NonText
[2]: https://vimhelp.org/syntax.txt.html#hl%2dEndOfBuffer
[3]: https://www.nordtheme.com/docs/ports/vim/customization
