### ISSUE TITLE
Disable transparency

### ISSUE THREAD

**Issue by huyhoang8398** [arcticicestudio/nord-vim#255]
I want to disable transparency while using nvim without disable transparency in terminal itself 
![image](https://user-images.githubusercontent.com/25379882/113498349-6f09ee00-950c-11eb-8f0e-42f8f4b07977.png)

**Comment by arcticicestudio** [comment]
Hi @huyhoang8398 :wave:

Rendering transparent/vibrant styles is part of the rendering engine, either by configuring it for the engine itself or within the terminal (which will use [window manager hints][1] to instruct the engine).
On Linux systems this can vary based in the used engine, e.g. the [opacity configurations when using _Picom_][2

A Vim theme is not responsible for styling these kind of things and there are no statements in this theme that do so.

[1]: https://en.wikipedia.org/wiki/Extended_Window_Manager_Hints
[2]: https://wiki.archlinux.org/index.php/Picom#Opacity

**Comment by arcticicestudio** [comment]
@huyhoang8398 have you been able to solve the problem? If so it would be nice if you could post the solution so other users who find this issue can also use it.

**Comment by arcticicestudio** [comment]
Closing for now, please feel free to reply if you'd like to follow up on this topic.
