### ISSUE TITLE
Comment contrast

### ISSUE THREAD

**Issue by octref** [arcticicestudio/nord-vim#26]
Feel the comment contrast is a bit too low:

![image](https://cloud.githubusercontent.com/assets/4033249/23582832/c0705750-0101-11e7-90ac-0e1f9c3295d5.png)

I'm setting it to `hi Comment ctermfg=14` temporarily, but hope you can resolve it.

![image](https://cloud.githubusercontent.com/assets/4033249/23582874/c5400c70-0102-11e7-9c25-09f291b1e698.png)

Not against the idea that comment should be in the same hue as bg, but the contrast needs to be higher.

**Comment by arcticicestudio** [comment]
👍 Thanks for your proposal, but this change is absolutely against the design idea of Nord.
The low contrast has been selected specifically to not disturb code flow and keep the focus of the developer on the code. Using a color like e.g. `nord7` for it would completely mix the separation between the code and comments. `nord7` is used for classes/types/interfaces/documentation tags and you would be unable to differ if it is part of the running code or just a comment.

It is totally fine that you not agree to all highlighting color assignments, everyone has different preferences.
If you'd like to stay with `nord7` (`ctermfg=14`, `guifg=14`) its totally fine and you don't have to change it in the theme file itself, which would be overriden each time you update your plugins.
Just paste this snippet into your `~/.vimrc` somewhere **before** you set the colorscheme via `colorscheme nord` and than add your custom syntax highlighting rules you want to override for the Nord Vim theme:
```vim
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight Comment ctermfg=14
augroup END
```

**Comment by octref** [comment]
I put this as my last sentence...

> Not against the idea that comment should be in the same hue as bg, but the contrast needs to be higher.

> to not disturb code flow

I respectfully disagree. Well-written comments either improve your reading/grasping of code much faster, and sometimes they are essential to understanding the intent of code.

It's actually pretty close to what I want. I just hope it's a bit lighter/whiter, so it's easier on the eyes.

**Comment by octref** [comment]
Ended up increasing iTerm 2 minimum contrast:

![image](https://cloud.githubusercontent.com/assets/4033249/23591914/835ac268-01c6-11e7-9f37-fb83f035e702.png)

Which increases contrast to make comments more legible.

![image](https://cloud.githubusercontent.com/assets/4033249/23591928/ca5e03a0-01c6-11e7-9fe1-4d9169d85155.png)

**Comment by arcticicestudio** [comment]
This is a nice alternative solution which is supported by many popular terminal emulators.
I'll add it to the project wiki 😉
