### ISSUE TITLE
Folded lines

### ISSUE THREAD

**Issue by Flamme13** [arcticicestudio/nord-vim#264]
Hello. Tell me how can I make the folded lines brighter?

Is that right or can you do better?
```
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight Folded guibg=CUSTOM_COLOR guifg=CUSTOM_COLOR
augroup END
```
found such a way in Issue for 2017
https://github.com/arcticicestudio/nord-vim/issues/36
can now be done differently?

Thank you!

**Comment by arcticicestudio** [comment]
Hi @Flamme13 :wave:
This is the recommended way to customize the theme like also described in the [Nord Vim “Customization“ documentation][1].

[1]: https://www.nordtheme.com/docs/ports/vim/customization

**Comment by Flamme13** [comment]
Thanks for the answer.
Cool theme!
