### ISSUE TITLE
Nord broken C++ highlighting

### ISSUE THREAD

**Issue by jay-patel-cognoai** [arcticicestudio/nord-vim#273]
![Screenshot from 2021-08-02 22-34-14](https://user-images.githubusercontent.com/83688544/127898227-63c2f593-3a5d-4321-b73f-157d54340424.png)

**Comment by jay-patel-cognoai** [comment]
Turns out it's an issue with TreeSitter

**Comment by arcticicestudio** [comment]
Hi @jay-patel-cognoai :wave:, thanks for your contribution :+1:

Looks like this is related to #269 which is currently in review and might be fixed in #270.

**Comment by arcticicestudio** [comment]
Resolved in #270.
