### ISSUE TITLE
VimScript Errors

### ISSUE THREAD

**Issue by IUseArrchBTW** [arcticicestudio/nord-vim#285]
**EDIT**: sorry, I realized that I don't know how to preserve line breaks within back ticks. If anyone could tell me how to better format my code I'd really appreciate it but in the meantime here is my question on paste bin: https://pastebin.com/i3fiu9bK

Hi, I installed nord-vim through vimplug like this:
`call plug#begin('~/.vim/plugged')
Plug 'arcticicestudio/nord-vim'
call plug#end()
colorscheme nord`
I then installed it with `PlugInstall`. Without chang the file at all, I run `vim` and I get a ton of errors:

`Error detected while processing /home/username/.vim/vimrc[44]../home/username/.vim/plugged/nord-vim/colors/nord.vim:  <br>
line   51:
E697: Missing end of List ']': 
line   52:
E10: \ should be followed by /, ? or &
line   53:
E10: \ should be followed by /, ? or &
line   54:
E10: \ should be followed by /, ? or &
line   55:
E10: \ should be followed by /, ? or &
line   56:
E10: \ should be followed by /, ? or &
line   57:
E10: \ should be followed by /, ? or &
line   58:
E10: \ should be followed by /, ? or &
line   59:
E10: \ should be followed by /, ? or &
line   60:
E10: \ should be followed by /, ? or &
line   61:
E10: \ should be followed by /, ? or &
line   62:
E10: \ should be followed by /, ? or &
line   63:
E10: \ should be followed by /, ? or &
line   64:
E10: \ should be followed by /, ? or &
line   65:
E10: \ should be followed by /, ? or &
line   66:
E10: \ should be followed by /, ? or &
line   67:
E10: \ should be followed by /, ? or &
line   68:
E10: \ should be followed by /, ? or &
line   69:
E10: \ should be followed by /, ? or &
line   70:
E10: \ should be followed by /, ? or &
line   71:
E10: \ should be followed by /, ? or &
line   72:
E10: \ should be followed by /, ? or &
line   73:
E10: \ should be followed by /, ? or &
line  121:
E10: \ should be followed by /, ? or &
line  122:
E10: \ should be followed by /, ? or &
line  644:
E697: Missing end of List ']': 
line  645:
E10: \ should be followed by /, ? or &
line  646:
E10: \ should be followed by /, ? or &
line  647:
E10: \ should be followed by /, ? or &
line  648:
E10: \ should be followed by /, ? or &
line  650:
E121: Undefined variable: s:clap_matches
Error detected while processing /home/username/.vim/plugged/vimtex/plugin/vimtex.vim:
line   13:
E10: \ should be followed by /, ? or &
`
In case its easier for you, these are the lines vim is complaining about:
`51 let s:nord3_gui_brightened = [
 52   \ s:nord3_gui,
 53   \ "#4e586d",
 54   \ "#505b70",
 55   \ "#525d73",
 56   \ "#556076",
 57   \ "#576279",
 58   \ "#59647c",
 59   \ "#5b677f",
 60   \ "#5d6982",
 61   \ "#5f6c85",
 62   \ "#616e88",
 63   \ "#63718b",
 64   \ "#66738e",
 65   \ "#687591",
 66   \ "#6a7894",
 67   \ "#6d7a96",
 68   \ "#6f7d98",
 69   \ "#72809a",
 70   \ "#75829c",
 71   \ "#78859e",
 72   \ "#7b88a1",
 73 \ ]`

`121                    \' The comment color brightness has been increased by 10% by default.' .
122                    \' Please see https://github.com/arcticicestudio/nord-vim/issues/145 for     more details.')`

`644 let s:clap_matches = [
645 
646         \ [s:nord8_gui,  s:nord8_term] ,
647         \ [s:nord9_gui,  s:nord9_term] ,
648         \ [s:nord10_gui, s:nord10_term] ,
649         \ ]
650 for s:nord_clap_match_i in range(1,12)`

Any ideas on what could be causing this issue?

**Comment by arcticicestudio** [comment]
Hi @IUseArrchBTW :wave:

In order to ensure the problem is related to the Nord theme you need to reproduce it with a minimal and clean configuration. This can be done by creating new configuration file with any name (e.g. `testrc`) and run Vim with the following command: `vim -u testrc`
For me as a theme author it is not possible to know if the theme is the root cause of the problem when there are other attributes set in the configuration because each one might break the theme.

Here's an minimal test configuration you can use to try to reproduce the problem (supposed you're using [vim-plug][]):

```vim
call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
call plug#end()

set nocompatible
if (has("termguicolors"))
  set termguicolors
endif

syntax enable
colorscheme nord
```

Could you please try to either use the example configuration to ensure that the error is not related to any other loaded code/plugin?
Also please provide some more information about your setup like the version of Vim and the OS you're running.

[1]: https://github.com/junegunn/vim-plug

**Comment by svengreb** [comment]
Closing this issue for now due to inactivity.
