### ISSUE TITLE
Incorrect hightlight

### ISSUE THREAD

**Issue by pirey** [arcticicestudio/nord-vim#30]
Hi,
I got incorrect highlight when editing a javascript file that contains following words `require`, `module`. Is there something to do with vim-javascript plugin? I'm using `pangloss/vim-javascript`

This only occurs in terminal vim, when I try it in macvim, the highlight is correct and the word is in _italic_. In the [readme](https://github.com/arcticicestudio/nord-vim#italic-comments) it is mentioned that italic is disabled by default, but it is only for comments. 

Is there any configuration I need to set to get correct highlighting?

Below is the picture, left is _iTerm2_, right is _MacVim_

![image](https://cloud.githubusercontent.com/assets/10344542/24340286/1c990f8c-12db-11e7-88ae-89a7002f139a.png)

Thanks

**Comment by arcticicestudio** [comment]
Everything should work out-of-the-box.
This may be related to any `vim`- or `tmux` plugin which makes changes to the syntax highlighting or at least uses any editor coloring functionality.
I tried to reproduce this problem and it works fine.

Have you tried to disable all other `vim` plugins and load the file outside of `tmux`?

**Comment by pirey** [comment]
Apparently, this was caused by this [vim-jsx-improve](https://github.com/neoclide/vim-jsx-improve) plugin

**Comment by arcticicestudio** [comment]
Good to hear that the problem is fixed.
I'll check the plugin and see if I can add optimized style support for it to fix the unintended highlighting.
