### ISSUE TITLE
Unable to setup Nord vim with packer.nvim

### ISSUE THREAD

**Issue by Felix-Kyun** [arcticicestudio/nord-vim#302]
I've been trying to install Nord vim on neovim with packer but am getting this error 
```
Error detected while processing /data/data/com.termux/files/home/.local/share/nvim/site/pack/pack
er/start/nord-vim/colors/nord.vim:
line  729:
E117: Unknown function: exist
line  862:
E117: Unknown function: exist
Press ENTER or type command to continue
```
I am using termux but I've tried it on my pc too and got the same results.
I am trying to write my config in Lua for the first so I am confused that if I messed smth

Thanks

**Comment by jvoisin** [comment]
This again, this should have been fixed by e2555c10c7f006f9a052419bc00056456731da6b
