### ISSUE TITLE
hightlight whole line on hightlighted Neovim health check text makes it disappear

### ISSUE THREAD

**Issue by syedelec** [arcticicestudio/nord-vim#31]
Hi,

I am using `neovim` with `colorscheme nord` (installed separately in `colors/` folder), I removed all plugins and personal configuration. `cursorline` is set to highlight the whole line.

Here is the result for `:CheckHealth`

![screenshot-20170510130722-941x329](https://cloud.githubusercontent.com/assets/9877335/25918825/a436f544-3581-11e7-8b2b-3e77660f7818.png)

Thanks.

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
Sorry for my late reply, I've been busy with my job.

Is this reproducible in Vim terminal- or GUI mode? The theme has not been optimized for NVim so there might be differences/problems.

**Comment by dylnmc** [comment]
It seems that the hl group is `healthStatus` in neovim.

![screenshot from 2017-07-16 19-55-04](https://user-images.githubusercontent.com/7635158/28252433-b1e68056-6a60-11e7-9fe1-b469cf5b12d3.png)

**Comment by dylnmc** [comment]
It's not just this colorscheme that is having issues, though:

![screenshot from 2017-07-16 20-08-57](https://user-images.githubusercontent.com/7635158/28252532-bcdf265a-6a62-11e7-8fed-04e44f473275.png)

Also, doing `:highlight healthStatus ctermfg=0 ctermbg=2` still had same problem (except worse):

![screenshot from 2017-07-16 20-11-37](https://user-images.githubusercontent.com/7635158/28252543-015613ac-6a63-11e7-9be5-daa5e94bc779.png)

I am going to check *freenode* / *neovim* to see if anyone knows about this and I will probably post an issue on neovim's gh.

**Comment by dylnmc** [comment]
After poking around on freenode for a bit, it may have something to do with https://github.com/neovim/neovim/pull/6380

I haven't really looked into it.

---

regards to sunjon on #vim on freenode

**Comment by dylnmc** [comment]
:highlight healthSuccess ctermfg=2 ctermbg=0
    :highlight healthWarning ctermfg=3 ctermbg=0
    :highlight healthSuccess ctermfg=1 ctermbg=0

seem to be ok, though.. (if this fits the style guidelines)

![screenshot from 2017-07-16 21-59-17](https://user-images.githubusercontent.com/7635158/28253458-348fb57a-6a72-11e7-9614-23017be53715.png)

---

Hopefully, this issue is resolved with neovim, though

**Comment by arcticicestudio** [comment]
Thanks again @dylnmc for your detailed investigation, it really helps a lot to get me tings done faster  :+1: 
I've created a PR for it.
