### ISSUE TITLE
search highlight on strings illegible

### ISSUE THREAD

**Issue by syedelec** [arcticicestudio/nord-vim#32]
Hi,

The same configuration as previous issue without `cursorline` set:
I am using `neovim` with `colorscheme nord` (installed separately in `colors/` folder), I removed all plugins and personal configuration.

During the search for a text between quotes, the highlighting color is incorrect (right)
Once I validate my search, the behavior is correct (left)
`incsearch` is activated by default

![screenshot-20170510134214-954x524](https://cloud.githubusercontent.com/assets/9877335/25920346/82857aec-3586-11e7-8563-8cc3f88d8b52.png)

Thanks.

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
Sorry for the late reply, I've been busy with my job.

I've pushed a fix for it.

<p align="center">Before<br><img src="https://user-images.githubusercontent.com/7836623/28238074-20069028-694c-11e7-985f-f46f8c343ac5.png"/><br>After<br><img src="https://user-images.githubusercontent.com/7836623/28238077-297ccec4-694c-11e7-91cf-dcaae7aefb6d.png"/></p>

@syedelec @dylnmc You can check out :seedling: [bugfix/gh-32-search-highlight-on-strings-illegible](https://github.com/arcticicestudio/nord-vim/tree/bugfix/gh-32-search-highlight-on-strings-illegible) to test the changes.

**Comment by dylnmc** [comment]
Folds still are not visible for me. Is that how they are supposed to look.

![screenshot from 2017-07-15 17-20-09](https://user-images.githubusercontent.com/7635158/28242744-f9b90b54-6981-11e7-92a8-0d03cdc68935.png)


Thanks for fixing the highlight on strings.

**Comment by arcticicestudio** [comment]
@dylnmc I've posted some information about the low contrast comment design in #36 .
The fold marker are indeed not optimal, I'll adjust them to match the comment color.

**Comment by syedelec** [comment]
The fix works on my neovim configuration, Thank you !
