### ISSUE TITLE
Theme looks weird on WSL

### ISSUE THREAD

**Issue by GeorgianStan** [arcticicestudio/nord-vim#320]
Hello!
I'm facing some issues with nord color scheme on WSL.
Here is screen shot of how my vim looks like and my **.vimrc** configuration.
![vimrc](https://user-images.githubusercontent.com/25796932/178241048-c4684763-de15-4cd5-90fd-9f93bbb715ac.PNG)

**Comment by svengreb** [comment]
Hi @GeorgianStan :wave:

It looks like you missed to install the actual color profile for the terminal you're using. WSL is just the technology that allows to use a Linux shell in Windows, but the application that renders it must be aware to the Nord colors. That is the reason why there are many [Nord port for various terminals][1]. When there is no official port (yet) you can search [the issues in the Nord repository][4] to see if the community created an unofficial port, e.g. see [#123][3] for [Windows Terminal][5] or [#90][3] for [PowerShell][6].

[1]: https://www.nordtheme.com/ports
[2]: https://github.com/arcticicestudio/nord/issues/123
[3]: https://github.com/arcticicestudio/nord/issues/90
[4]: https://github.com/arcticicestudio/nord/issues
[5]: https://github.com/microsoft/terminal
[6]: https://github.com/PowerShell/PowerShell

**Comment by svengreb** [comment]
Have you been able to fix your setup using a community-created terminal port?

**Comment by GeorgianStan** [comment]
Hi @svengreb, I was able to create a new Theme Color inside Windows Terminal (WSL) using the same colors from Nord Theme and now it's working fine.
