### ISSUE TITLE
TODO highlight incorrect

### ISSUE THREAD

**Issue by KevinSjoberg** [arcticicestudio/nord-vim#34]
I'm running [Neovim](https://neovim.io/) (NVIM v0.2.0). `TODO` items are highlighted in a very awful looking yellow color.

![screen shot 2017-06-16 at 19 04 58](https://user-images.githubusercontent.com/503025/27236877-fdfa37fa-52c6-11e7-8c60-40c6af84e46b.png)

Running `:highlight Todo`:

![screen shot 2017-06-16 at 19 07 48](https://user-images.githubusercontent.com/503025/27236924-39683cec-52c7-11e7-9190-ee02619b84b2.png)

In the [colorscheme](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L173) we see that `guibg` is set to `""` and `ctermbg` is set to `NONE`. We probably want to set this to something relevant.

I'd be happy to submit a pull request. Just need to know what colors we should be using.

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
Sorry for the late reply, I've been busy with my job.

The background should be "transparent", that's the reason why I've set it to "NONE" which works fine for me in NVim and Vim in both terminal- and GUI mode.

![gh-34-scrot-vim-terminal-mode](https://user-images.githubusercontent.com/7836623/28237636-54dec0ac-6944-11e7-832c-2e20628a8484.png)

The yellow color on your screenshot is also not the one defined in Nord so maybe there is a setup problem.

Which OS and terminal emulator are you running?

**Comment by KevinSjoberg** [comment]
@arcticicestudio we can close this. I'm not sure what caused it, but I'm not seeing this anymore.

**Comment by arcticicestudio** [comment]
@KevinSjoberg I don't know why you had this issue randomly, but #53 finally fixes it :smile:
