### ISSUE TITLE
Can't get theme working in VIM 9.0.1499

### ISSUE THREAD

**Issue by blixelcode** [arcticicestudio/nord-vim#348]
I'm using VIM 9.0.1499 on a Raspberry Pi. I've been using the Dracula theme, but when I saw the Nord theme, I wanted to try it out. However, when I switch to the theme ... this is what it looks like for me:

![2024-01-02_07-42-12](https://github.com/nordtheme/vim/assets/154928122/3dd505fb-9d21-469a-b2b6-8d91ece1d277)

Does anyone have any suggestions for how I can get the Nord theme working correctly?

Thanks

**Comment by ericvw** [comment]
@blixelcode, have you also configured your terminal emulator colors to the Nord theme palette?

The instructions at https://www.nordtheme.com/docs/ports/vim/installation indicates:

> Vim in terminal mode must be used with a [Nord terminal emulator theme](https://www.nordtheme.com/ports) in order to work properly!
> 
> Make sure to install one of the currently supported [terminal emulator port projects](https://www.nordtheme.com/ports) **before** installing Nord Vim.
> 
> Vim in terminal mode uses the 16 color codes provided by the terminal emulator.
> When used with another color theme than the one provided by one of Nord's terminal emulator ports, the colors in Vim won't use [Nord's color palettes](https://www.nordtheme.com/docs/colors-and-palettes)!
> This will result in different styles than those defined by Nord Vim and could make it appear that there is a problem with the Nord Vim theme while the actual problem are missing Nord colors.
> 
> Read the GitHub Gist about [terminal colors](https://gist.github.com/XVilka/8346728) for more information about terminal color specifications.

I'm guessing the colors you are seeing are the same colors as the colors on your terminal.
