### ISSUE TITLE
Adjust fold marker color

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-vim#38]
> **Related to** #36 

The fold marker are currently using nord1 as foreground color. This is too dark causing them to be unreadable in bright environments and should be adjusted to match the color of comments.

---

\cc @syedelec

**Comment by dylnmc** [comment]
Hi, I am sorry to have tried to tell you what colors to use in my first issue. :sob: I hadn't understood the scope of this color scheme as I was just fiddling with it at the end of a long day of work on Thursday (?) night.

I do have an additional concenr, however. I think that having comments and folding have the same background is quite confusing (especially if they have the same foreground). Would it be in your budget to allow for a very low-contrast background for folding? Or is that something I should specify myself?

Thanks for being so proactive (and sorry again :'D).

**Comment by arcticicestudio** [comment]
Sure I've also thought about the same after creating the PR, just wanted to wait for your feedback :smile:
