### ISSUE TITLE
Error while loading in terminal

### ISSUE THREAD

**Issue by kamwitsta** [arcticicestudio/nord-vim#4]
The theme is great but when I run it in Gnome Terminal 3.22.1, I get this:

`Error detected while processing function <SNR>50_hi:`
`line   17:`
`E254: Cannot allocate colour 1`
`E254: Cannot allocate colour 3`
`E254: Cannot allocate colour 7`
`E254: Cannot allocate colour 15`

The theme seems to load nonetheless. I suppose it might be about the guisp parameter.

**Comment by arcticicestudio** [comment]
Thanks for your report.
Which OS and Vim version are you running?
In which mode (terminal/GUI) does the error occur?

I was not able to reproduce this for both modes, Vim starts without errors using version `8.0.0086`.

**Comment by ipelekhan** [comment]
The same here. I am using ```vim-8.0.0134``` under MacVim GUI on macOS. After this error I am able to press enter and theme loads, except lightline.vim still has default colors.

PS @arcticicestudio could you please share your vim/OS specs and .vimrc? I'd like to get the same look for myself 😏

**Comment by arcticicestudio** [comment]
I was able to reproduce it now too.
I'm on Arch Linux running the normal [`vim`](https://www.archlinux.org/packages/extra/x86_64/vim) package which has different compile flags as the [`gvim`](https://www.archlinux.org/packages/extra/x86_64/gvim) package that is also compiled with GUI support and includes the default terminal vim too.

I had no errors with the default `vim` package, but the `gvim` package raised the errors listed above.
I checked the documentation of the flags and it seems like the `gvim` package is more verbose when it comes to logging. The default `vim` package suppresses the errors and ignores malformed code, while the `gvim` package logs it to the user and ignores the malformed code when the user presses a key.

In the end it turned out this is a bug in the Nord Vim theme file.
As mentioned by @kamwitsta, the `guisp` attribute had the wrong color codes.
The four `Spell*` attributes where set to use `*_term`- instead of `*_gui` color variables for the `undercurl` style.

I'll release a patch version to fix this.

@ipelekhan Thanks for your help too. I checked the homebrew build  script for the MacVim package quickly and hope this will fix it on macOS too.
I'll post all relevant `.vimrc` configs after fixing this issue.

**Comment by arcticicestudio** [comment]
I've released version [`0.1.1`](https://github.com/arcticicestudio/nord-vim/releases/tag/v0.1.1) to fix this issue.
If you've installed Nord Vim via vim-plug you can easily update via `:PlugUpdate`.

@ipelekhan 
Here are all relevant config which affect the appearance of my Vim setup.

**Base configss**
```viml
set nocompatible
filetype plugin on
filetype indent on
syntax enable
```

**UI configs**
```viml
set wildmenu
set noshowmode
set number

set ruler
set showmatch
set list

set colorcolumn=160
set cursorline
set guicursor=n-i-v-c-a:iCursor

set laststatus=2

set hlsearch
set incsearch
set smartcase

set magic

set gfn=Source\ Code\ Pro\ Regular\ 8
set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L
set guicursor=a:ver25-Cursor/lCursor

colorscheme nord
```

**Plugins**  
```viml
call plug#begin(expand('~/.vim/plugged'))
Plug 'scrooloose/nerdtree'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
Plug 'Yggdroot/indentLine'
Plug 'itchyny/lightline.vim'
Plug 'pangloss/vim-javascript'
Plug 'gorodinskiy/vim-coloresque'
Plug 'arcticicestudio/nord-vim'
call plug#end()
```

**GitGutter configuration**  
```viml
let g:gitgutter_sign_column_always = 1
let g:gitgutter_realtime = 1
let g:gitgutter_eager = 1
set updatetime=250
```

**`pangloss/vim-javascript` configuration**  
```viml
let g:javascript_enable_domhtmlcss = 1
```

**`lightline.vim` configuration**  
```viml
let g:lightline = {
      \ 'colorscheme': 'nord',
      \ 'active': {
      \   'left': [
      \     [ 'mode', 'paste' ],
      \     [ 'fugitive', 'filename' ]
      \   ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightlineFugitive',
      \   'readonly': 'LightlineReadonly',
      \   'modified': 'LightlineModified',
      \   'filename': 'LightlineFilename'
      \ },
      \ 'separator': {
      \   'left': '',
      \   'right': ''
      \ },
      \ 'subseparator': {
      \   'left': '',
      \   'right': ''
      \ }
    \ }

function! LightlineModified()
  if &filetype == "help"
    return ""
  elseif &modified
    return "+"
  elseif &modifiable
    return ""
  else
    return ""
  endif
endfunction

function! LightlineReadonly()
  if &filetype == "help"
    return ""
  elseif &readonly
    return "⭤"
  else
    return ""
  endif
endfunction

function! LightlineFugitive()
  if exists("*fugitive#head")
    let branch = fugitive#head()
    return branch !=# '' ? ' '.branch : ''
  endif
  return ''
endfunction

function! LightlineFilename()
  return ('' != LightlineReadonly() ? LightlineReadonly() . ' ' : '') .
       \ ('' != expand('%:t') ? expand('%:t') : '[No Name]') .
       \ ('' != LightlineModified() ? ' ' . LightlineModified() : '')
endfunction
```

**`pangloss/vim-javascript` configuration**  
```viml

**Comment by ipelekhan** [comment]
Thanks for the update. I can confirm that there are no errors either in iTerm terminal or MacVim gui app now.
For some reason on my Mac ```set colorscheme nord``` takes no effect in MacVim and by default colorscheme is set to MacVim's default, but adding this line helps:
```
let macvim_skip_colorscheme=1
```

@arcticicestudio, thanks a lot for your work! Nord theme for vim is so awesome, so I can finally switch to vim from atom permanently 😎
Let me ask you a one more question, could you share your ```listchars``` config? Or please give some hints how to make vim to show those invisible spaces as dots? I have googled some solutions, but all of them were far from what I saw on your screenshots. Thanks in advance!

**Comment by arcticicestudio** [comment]
Thanks, nice to hear you like it 😄 
Good to know that there are small differences between vim and MacVim, I'll add it to the "Activation" section of the README.

And here's my `listchars`:  
```viml
set listchars=eol:¬,space:·,tab:»\
```

**Comment by kamwitsta** [comment]
I confirm the theme loads correctly now. Thanks for the great work!
