### ISSUE TITLE
vim-plug support

### ISSUE THREAD

**Issue by dylnmc** [arcticicestudio/nord-vim#43]
`plugDeleted` links to `Ignore` and the result is invisible unless you have `:set cursorline` enabled and are on that line:

---

![plug1](https://user-images.githubusercontent.com/7635158/28279603-016410ba-6aef-11e7-956e-9e2d3c22cd34.PNG)
![plug2](https://user-images.githubusercontent.com/7635158/28279649-1adb51d4-6aef-11e7-9563-d94bfd7a4ab3.PNG)

---

changing `ctermfg` to `s:nord3_term` and `guibg` to `s:nord3_gui` for `Ignore` seems like a good fix.

**Comment by arcticicestudio** [comment]
Which OS, version of Vim/Neovim/Gvim and terminal emulator are you running?
I've tried to reproduce this but the line is visible whether with `cursorline` enabled or not.

![gh-43-scrcast-vim-plug-clean](https://user-images.githubusercontent.com/7836623/28317440-27c56cda-6bc7-11e7-8de5-e9d3821eb9c0.gif)

**Comment by dylnmc** [comment]
Ok, I will check it out when I get back home. I was noticing this in gvim at work, but I work in regular ole vim at home in urxvt, and I don't think I have noticed it there. Maybe it has something to do with the gui hl groups. Thanks

**Comment by dylnmc** [comment]
This is set to correct color in term, but in gvim, it's invisible because `plugDeleted` links to `Ignore` which is set to `ctermfg=0` ctermbg=bg` by default.

**Comment by arcticicestudio** [comment]
I'll try to reproduce it in gvim.

**Comment by arcticicestudio** [comment]
I've implemented optimized support for vim-plug in #59.
