### ISSUE TITLE
Support for plasticboy/vim-markdown

### ISSUE THREAD

**Issue by VVVFO** [arcticicestudio/nord-vim#45]
The highlighting for Markdown will stop to work once 'plasticboy/vim-markdown' is installed. Could it be because they have a different system of syntax naming? I never had any Markdown highlighting problem with other color schemes before.

Expected:
<img width="1440" alt="screen shot 2017-07-27 at 1 04 25 am" src="https://user-images.githubusercontent.com/10219026/28631281-9d13c4f4-7267-11e7-90bb-715a22bc4cc1.png">

Actual:
<img width="1440" alt="screen shot 2017-07-27 at 1 03 02 am" src="https://user-images.githubusercontent.com/10219026/28631294-a40531da-7267-11e7-8c74-14847d1cb0dc.png">

**Comment by arcticicestudio** [comment]
Thanks for your report :+1: 
I'll try to reproduce this within the next days, but my guess is that they are using a custom variable namespace which needs to be implemented as plugin support into this theme.

**Comment by powelleric** [comment]
Just confirming that I also am experiencing this behavior.  Switching to a different colorscheme resolves the issue....whatever that is.

**Comment by powelleric** [comment]
I think you are correct about the "custom variable namespace".  I looked through the repository OP linked to and in the `syntax/markdown.vim` file I saw this type of stuff.

```
"HTML headings
syn region htmlH1       start="^\s*#"                   end="$" contains=mkdLink,mkdInlineURL,@Spell
syn region htmlH2       start="^\s*##"                  end="$" contains=mkdLink,mkdInlineURL,@Spell
syn region htmlH3       start="^\s*###"                 end="$" contains=mkdLink,mkdInlineURL,@Spell
syn region htmlH4       start="^\s*####"                end="$" contains=mkdLink,mkdInlineURL,@Spell
syn region htmlH5       start="^\s*#####"               end="$" contains=mkdLink,mkdInlineURL,@Spell
syn region htmlH6       start="^\s*######"              end="$" contains=mkdLink,mkdInlineURL,@Spell
```
Anyway, not sure if that is a lot of work to implement but it would be really appreciated.

**Comment by powelleric** [comment]
I was able to get some basic highlighting working with the custom variable namespace.  I added these lines at line 304 of `colors/nord.vim` and it seems to work.

It would be great to get more of this namespace mapped to nord because this seems to be a quite popular vim plugin (+2000 stars).

Here is a link to the syntax file showing other regions that need to be mapped, https://github.com/plasticboy/vim-markdown/blob/master/syntax/markdown.vim

```

hi! link htmlH1 markdownH1
hi! link htmlH2 markdownH1
hi! link htmlH3 markdownH1
hi! link htmlH4 markdownH1
hi! link htmlH5 markdownH1
hi! link htmlH6 markdownH1
hi! link mkdListItem markdownListMarker
hi! link mkdListItemLine markdownListMarker
hi! link mkdBold Bold
hi! link mkdItalic Italic
```

**Comment by arcticicestudio** [comment]
@VVVFO  @powelleric Sorry for the delay, I've had no time to work on my projects. I've opened PR #57 which implements support for the plugin. It would be nice if you can test the changes and see if it works and you'd expect it to be highlighted.

**Comment by VVVFO** [comment]
Justed tested, it worked perfectly! Thank you for your work @arcticicestudio !
