### ISSUE TITLE
Color for bash variables

### ISSUE THREAD

**Issue by powelleric** [arcticicestudio/nord-vim#47]
First off, thanks so much for this colorscheme.  This is easily my favorite colorscheme ever.  I'm obsessed.

![screen shot 2017-08-25 at 9 57 20 am](https://user-images.githubusercontent.com/11025490/29721946-2a3c00aa-897c-11e7-9e48-feca7b754943.png)

In the screenshot below, there is the same block of text in nord and in elflord.  You can see that the `$TERM` and `color_prompt` variables are not distinguished by any color.

I would really like to see a color for these bash variables.  I don't care which color.  You are obviously great at choosing colors.  Just anything to distinguish the variables from text.

**Comment by dylnmc** [comment]
Hi, @powelleric 

You can fix this in your vimrc. After the line where you call `colorscheme nord`, you can put the following:

```vim
highlight shDerefSimple ctermfg=6 guifg=#88C0D0
highlight shDerefVar ctermfg=6 guifg=#88C0D0
```

(for example)

---

You can change those to any colors that you desire (term: `0=black`; `1=red`; `2=green`; `3=yellow`; `4=blue`; `5=magenta`; `6=cyan`; `7=white`) (gui: `#3B4252=black`; `#BF616A=red`; `#A3BE8C=green`; `#EBCB8B=yellow`; `#81A1C1=blue`; `#B48EAD=magenta`; `#88C0D0=cyan`; `#E5E9F0=white`)

**Comment by powelleric** [comment]
Interesting.  I arrived at a different solution.  

It seems that `Identifier` has no color ("NONE") when used in term mode.  Changing it to an actual color fixed seems to have produced roughly the same result as you have.

In fact,  'Identifier' is not the only thing that has NONE for a terminal color while having a color set for GUI.
I wonder is why any syntax objects that get colors in the GUI shouldn't also get colors in a terminal.  Maybe I am just misunderstanding how the colors are set...  

```
diff --git a/colors/nord.vim b/colors/nord.vim
index 3b30d93..6f06254 100755
--- a/colors/nord.vim
+++ b/colors/nord.vim
@@ -158,7 +158,7 @@ call s:hi("Delimiter", s:nord6_gui, "", s:nord6_term, "", "", "")
 call s:hi("Exception", s:nord9_gui, "", s:nord9_term, "", "", "")
 call s:hi("Float", s:nord15_gui, "", s:nord15_term, "", "", "")
 call s:hi("Function", s:nord8_gui, "", s:nord8_term, "", "", "")
-call s:hi("Identifier", s:nord4_gui, "", "NONE", "", "NONE", "")
+call s:hi("Identifier", s:nord4_gui, "", s:nord7_term, "", "NONE", "")
 call s:hi("Include", s:nord9_gui, "", s:nord9_term, "", "", "")
 call s:hi("Keyword", s:nord9_gui, "", s:nord9_term, "", "", "")
 call s:hi("Label", s:nord9_gui, "", s:nord9_term, "", "", "")
```

**Comment by dylnmc** [comment]
colors are set like this `function! s:hi(group, guifg, guibg, ctermfg, ctermbg, attr, guisp)`. So, it looks like you added them in the correct spot.

I concur that it is weird to set it to `NONE` .. when you do so (for foreground at least), it changes it to white (usually--if not then whatever your default foreground color is, but in this case it is white).

@arcticicestudio :confused: why you do dis

**Comment by arcticicestudio** [comment]
The terminal is limited to 16 colors and depends on the color scheme of the terminal emulator. `NONE` is the same as `nord4_gui` since the default color for [the available terminal emulator color schemes](https://github.com/arcticicestudio/nord-vim#installation) is `nord4`, but there is no number for the default color (0-15) that could be assigned to a `nord4_term` variable. The default color is special from the viewpoint that it is activate as soon as there is no other color number assigned, so literally `NONE`.

**Comment by arcticicestudio** [comment]
@powelleric Like @dylnmc already posted above the correct way to customize the theme is to override specific parts of it, but instead of using a `*` character you should replace it with `nord` to only apply the overrides to the Nord theme.

```vim
augroup nord-overrides
    autocmd!
    autocmd ColorScheme nord highlight "...
augroup END
```

You can name the `augroup` whatever you want.

**Comment by arcticicestudio** [comment]
I'll check the color definitions for shellscripts to see if it can be improved.

**Comment by powelleric** [comment]
Thank you @dylnmc @arcticicestudio 

Below is the snippet I am using based on your recommendations.  Seems to be working just fine.

```
augroup nord
    autocmd!
    autocmd ColorScheme nord highlight shDerefSimple ctermfg=6 guifg=#88C0D0
    autocmd ColorScheme nord highlight shDerefVar ctermfg=6 guifg=#88C0D0
    autocmd ColorScheme nord highlight shVariable ctermfg=6 guifg=#88C0D0
augroup END

```
