### ISSUE TITLE
diff very high contrast

### ISSUE THREAD

**Issue by dylnmc** [arcticicestudio/nord-vim#49]
Is the diff supposed to look like this?

![screenshot from 2017-09-15 20-46-59](https://user-images.githubusercontent.com/7635158/30507797-7cf527c2-9a57-11e7-8d33-388871ddfd01.png)
![screenshot from 2017-09-15 20-48-40](https://user-images.githubusercontent.com/7635158/30507798-7cfa1a66-9a57-11e7-8a45-25408c8020f3.png)

I am trying to think of a better, low-contrast option, but I am not sure I can think of any since all of the colors (besides black) are fairly high contrast.

---

there is still probably a better option; I might make a pull request tomorrow if I don't hear or get the go-ahead..

**Comment by dylnmc** [comment]
It looks like it's intentional since they are explicitly set

But it hurts my eyes

**Comment by arcticicestudio** [comment]
This should be definitely be changed, either by using a dark foreground color for all marked sections or I'll change the colors for the diff to be almost transparent.

**Comment by arcticicestudio** [comment]
Thanks for your PR :+1: 

Using `nord1` as background seems like a nice and clean solution making the diffs visually noticeable without being too noisy, but maybe users are used to a colorful diff view.

I think we should implement this as another theme configuration so users can decide whether they want to use a colorful or uniform diff view background.

The colorful diff views uses the current colors for *added*, *changed* and *deleted* diff elements and the default background color (`nord0`). Then the `reverse` attribute is applied which results in a colored background and a dark background.

![gh-49-scrot-preview-colorful-after](https://user-images.githubusercontent.com/7836623/30955203-19fe61f2-a433-11e7-9d26-cca038e52e54.png)

The colorful diff view should be default which can be changed to your implementation from #50 via a new `g:nord_uniform_diff_background` config.

**Comment by arcticicestudio** [comment]
> Superseded by #60
