### ISSUE TITLE
g:colors_name is not set

### ISSUE THREAD

**Issue by shuei72** [arcticicestudio/nord-vim#5]
`g:colors_name` is not properly set.
```vim
:colorscheme nord
:colorscheme
default

:echo g:colors_name
E121: Undefined variable: g:colors_name
```
[`g:colors_name`](https://github.com/arcticicestudio/nord-vim/blob/f3330e8136d0a5cb13e256d1ee658ea5fcc6021a/colors/nord.vim#L9) should be set after [`syntax reset`](https://github.com/arcticicestudio/nord-vim/blob/f3330e8136d0a5cb13e256d1ee658ea5fcc6021a/colors/nord.vim#L47).

**Comment by arcticicestudio** [comment]
Thanks for your report, it has been fixed and merged into recently published the release version [`0.1.2`](https://github.com/arcticicestudio/nord-vim/releases/tag/v0.1.2).
