### ISSUE TITLE
Todo bright background

### ISSUE THREAD

**Issue by dylnmc** [arcticicestudio/nord-vim#52]
Background for `Todo` isn't set manually and looks bad.

![todo_pretty](https://user-images.githubusercontent.com/7635158/30652130-926379b4-9df5-11e7-930f-5b27d38fee2b.png)
![todo_ugly](https://user-images.githubusercontent.com/7635158/30652129-9262aac0-9df5-11e7-9ee5-0350e3de9d18.png)

It looks good when `cursorline` is on, and you're on that line, but it looks bad when you move away.

I'll make pull request when I get home ... I'll just set background for term and gui to `NONE`, and hopefully, that'll do the trick.

cheers 😄

(ps if you don't see it in vim, I'm in gvim 😢 at work)

**Comment by dylnmc** [comment]
looks like it was only for gvim. fixed it though.

![todo_fixed](https://user-images.githubusercontent.com/7635158/30670778-ac14f3ce-9e31-11e7-8e3e-cf4f805caca7.png)

**Comment by arcticicestudio** [comment]
Thanks for the fix :+1:

I need to remind myself to test in vim, neovim/macvim and gvim :smile: 

This also confirms that #37 was affected by this too.

/cc @KevinSjoberg
