### ISSUE TITLE
vim tab completion highlight

### ISSUE THREAD

**Issue by markand** [arcticicestudio/nord-vim#64]
Hello,

Using your awesome vim color theme I have a small issue regarding the tab completion selector.

In fact, there is no different color when doing completion, see screenshot:

![screen shot 2017-10-23 at 11 41 37 am](https://user-images.githubusercontent.com/11919008/31882466-2b9f98f0-b7e7-11e7-9aea-613a2e89da7a.png)

**Comment by dylnmc** [comment]
Hi, markand.

Do you, by any chance, do `highlight StatusLine ctermbg=8` in your vimrc?

If not, can you show the output of `:hi StatusLine`?

By default, it should looke like this:

![tmp](https://user-images.githubusercontent.com/7635158/31917951-39ae0c74-b828-11e7-9ca2-8cc5f4369cad.png)

**Comment by markand** [comment]
Hello,

No I don't have any `hi` command in my [vimrc (see it)](http://hg.markand.fr/dotfiles/file/tip/.vimrc).

But `hi StatusLine` shows ctermbg=8.

    StatusLine     xxx term=bold,reverse ctermfg=6 ctermbg=8 guifg=#88C0D0 guibg=#4C566A

I use vim8 on Terminal.app (which I have imported your awesome color scheme too)

**Comment by arcticicestudio** [comment]
Is it reproducible with `:set termguicolors`?

**Comment by markand** [comment]
I don't know if the colors are correct but I don't get a different background:

![screen shot 2017-10-24 at 9 26 15 am](https://user-images.githubusercontent.com/11919008/31929800-8e070da0-b89d-11e7-9846-a16470e83157.png)

**Comment by markand** [comment]
Okay I'm sorry I've tested with the 0.6.0 version and everything works fine! It looks like the issue is only coming from master version.

**Comment by arcticicestudio** [comment]
Alright, might be fixed through #58.
I'll try to release version [0.7.0](https://github.com/arcticicestudio/nord-vim/projects/10) till the end of the week.

**Comment by arcticicestudio** [comment]
It turns out that this is a bug introduced with #58.
The implemented feature in this PR changed the background color of the status bar (`StatusLine`) group to `nord3`, but the `WildMenu` group also uses `nord3` as background color for the current tab selection.

The solution is to change the `WildMenu` background color to `nord1` which is available for both terminal (`nord1_term`) and GUI (`nord1_gui`) mode.
