### ISSUE TITLE
Add highlight support for diffAdded and diffRemoved

### ISSUE THREAD

**Issue by brandoniffert** [arcticicestudio/nord-vim#66]
<img width="545" alt="screen shot 2017-10-25 at 8 53 58 am" src="https://user-images.githubusercontent.com/160448/31999727-539b0750-b962-11e7-9bf7-2c764015aa30.png">

vs

<img width="537" alt="screen shot 2017-10-25 at 8 50 45 am" src="https://user-images.githubusercontent.com/160448/31999729-551b0a26-b962-11e7-94ce-fb2abefd58d7.png">

**Comment by dylnmc** [comment]
It's `DiffAdd`, `DiffChange` and `DiffDelete` in *vim*.

Are you in *neovim*? Also, how did you get to this diff? Did you use `:diffthis` or something? Or is this a plugin?

Thanks,
m1n

---

If you're in neovim, and tthis is a real thing, I'll symlink `DiffAdded` to `DiffAdd` and `DiffDeleted` to `DiffDelete` when I get home.

**Comment by arcticicestudio** [comment]
Thanks for your contribution, but the theme already supports highlighting for `diff`. The groups are named [`diffAdd`][add] and [`diffDelete`][del].

![](https://raw.githubusercontent.com/arcticicestudio/nord-vim/develop/assets/scrot-config-uniform-diff-default.png)

The theme also provides a configuration to enable [uniform diff background][uni].

![](https://raw.githubusercontent.com/arcticicestudio/nord-vim/develop/assets/scrot-config-uniform-diff.png)

I've searched the [official vim documentation][docs], but the only groups listed are `diffAdd` and `diffDelete`. 

@brandoniffert  Is there any documentation about the groups you mentioned or are they maybe added by a plugin you're using?

[add]: https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L298
[del]: https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L299
[uni]: https://github.com/arcticicestudio/nord-vim#uniform-diff-background
[docs]: http://vimdoc.sourceforge.net/htmldoc/syntax.html#hl-DiffAdd

**Comment by brandoniffert** [comment]
Hmm, I can't seem to find docs on it either but I've had it in other colorschemes. It's in the vim source code for [git.vim and diff.vim](https://github.com/vim/vim/search?utf8=%E2%9C%93&q=diffAdded&type=)

I have vim set to my `$EDITOR` and when I run `git commit --verbose` it opens it in vim to edit and that's where I see this interface.

**Comment by arcticicestudio** [comment]
Ah, I see :eyes: 

I've scoured through the git log and saw that it was included in an earlier version, but got removed because it seemed like a deprecated group since it had no effect when used with `vim -d` / `:diff`.

I'll link the missing groups to their respective `diff*` group.

**Comment by arcticicestudio** [comment]
Linked [`diffAdded` and `diffRemoved`][add-rem] to their respective groups and the [`diffChanged`][changed] group to `DiffChange`.

[add-rem]: https://github.com/vim/vim/search?q=diffAdded+diffRemoved
[changed]: https://github.com/vim/vim/search?q=diffChanged
