### ISSUE TITLE
Add lightline theme to lightline repository

### ISSUE THREAD

**Issue by lokesh-krishna** [arcticicestudio/nord-vim#68]
Could you consider adding the lightline theme to the lightline repository to offer a more seamless experience?

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1:

:arrow_right: itchyny/lightline.vim#257

Sounds like a good idea and won't increase the maintenance effort since the file is not going o be be changed as long as there are no new lightline color scheme features.

**Comment by lokesh-krishna** [comment]
I am just so impressed by how meticulous and organized you and this entire project is. It is beautiful :)  
And thanks :)

**Comment by arcticicestudio** [comment]
Thanks for your compliment, sometimes it's not easy to get some free time next to my job to manage all these things, but I :heart: Open Source and GitHub so it's worth every second :smile: 

The linked PR will be merged as soon as arcticicestudio/nord#55 is completed which is related to the response of the lightline repository owner posted in the PR.

**Comment by arcticicestudio** [comment]
itchyny/lightline.vim#257 has been merged and is now available in the lightline `master` branch.
