### ISSUE TITLE
Adjust visual (selection) colour

### ISSUE THREAD

**Issue by scottwillmoore** [arcticicestudio/nord-vim#7]
The visual selection colour defined by, [`call s:hi("Visual", "", s:nord2_gui, "", s:nord3_term, "", "")`](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L98) uses the same colour, `s:nord3_term` as comments do. This means that when selecting comments with visual regions you cannot read the selected area.

This could be easily resolved by making the visual region use the colour, `s:nord1_term`. This colour does not appear to clash with other syntax elements, and hence should be a better choice the visual region colour.

**Comment by arcticicestudio** [comment]
Thanks for your report 👍 
Even if comments are hard to read with`nord1` as smooth and easy-on-the-eyes background color, it seems like it is the only solution to keep the style guideline with other port projects.

You can test the change by checking out the [`improvement/ghi-#7-adjust-visual-selection-colour`](https://github.com/arcticicestudio/nord-vim/tree/improvement/ghi-%237-adjust-visual-selection-colour) branch.

**Comment by scottwillmoore** [comment]
Awesome, thank you for that!

Others may want to add the following patch to their `.vimrc` until a release is prepared (which I'm sure won't take long).

````
autocmd ColorScheme * highlight Visual ctermbg=0
````

**Comment by arcticicestudio** [comment]
🚢 Shipped in release version [0.2.0](https://github.com/arcticicestudio/nord-vim/releases/tag/v0.2.0) 😄

**Comment by clearissimple** [comment]
Would it be possible to adjust the style of visual selection to be a little more dominant in diff mode?
![screenshot from 2018-10-25 11-28-22](https://user-images.githubusercontent.com/13639560/47490899-f1752a80-d849-11e8-84f8-00e2e22f4e0f.png)
In the screen shot above all but the last line are selected in the visual line selection mode.

**Comment by arcticicestudio** [comment]
@clearissimple Have you tried if it works fine using the [uniform diff background][c] theme configuration?

[c]: https://github.com/arcticicestudio/nord-vim#uniform-diff-background

**Comment by clearissimple** [comment]
Yes, it works. The uniform diff background mode is nice, too.
