### ISSUE TITLE
Pair "brackets" looks bad

### ISSUE THREAD

**Issue by cryptomaniac512** [arcticicestudio/nord-vim#71]
![image](https://user-images.githubusercontent.com/10251687/32930139-7363a1ac-cba8-11e7-9325-f6638e9f35f3.png)
In this screenshow cursor is on `<div`, but looks like it set on `>`

Can it be fixed?

**Comment by arcticicestudio** [comment]
Have you tried to reproduce it without any plugin enabled?

I've tried to reproduce this, but it works fine on my system.

![gh-71-scrot-reproduction](https://user-images.githubusercontent.com/7836623/32935432-751664e0-cb70-11e7-8e06-321618365bbe.png)

**Comment by cryptomaniac512** [comment]
Yes, it looks like this.

But it's not clear where the cursor is. I think that the highlighted pair should be paler.

Now when navigating, it creates the feeling that the cursor is jumping over the text and it distracts attention.

**Comment by arcticicestudio** [comment]
I think this more a kind of personal preference and also depends on the used shell/terminal emulator. It is totally fine that you not agree to all highlighting color assignments, everyone has different preferences.

If you'd like to change the bracket matching highlighting add this snippet into your `~/.vimrc` somewhere before you set the color scheme (`colorscheme nord`) and modify the values to fit your needs:

```vim
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight MatchParen ctermbg=6 ctermfg=0 guibg=#88C0D0 guifg=#2E3440
augroup END
```
**Note that this will only apply to the Nord color scheme and won't effect other color schemes!**

Reload Vim or run `:colorscheme nord` to see the changes.

Another solution might be to configure your shell/terminal emulator. I use zsh and [Tilix][t] which works fine when configuring the cursor to be well recognizable (Tilix also allows me to configure dynamic profiles which will be enabled when e.g. Vim is running and makes the cursor larger and bold).

[t]: https://gnunn1.github.io/tilix-web/

**Comment by cryptomaniac512** [comment]
@arcticicestudio oh, I try it and nothing changed :(

**Comment by cryptomaniac512** [comment]
For example, now cursor at `}`
![image](https://user-images.githubusercontent.com/10251687/32937341-d3597bac-cbc3-11e7-9f78-a4dbc0477b79.png)

Part of my `init.vim`
```VimL
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight MatchParen ctermbg=6 ctermfg=0 guibg=#88C0D0 guifg=#2E3440
augroup END
colorscheme nord
```

**Comment by cryptomaniac512** [comment]
Help me, please. I don't understand how ti fix this.
I use neovim and xfce4-terminal

**Comment by arcticicestudio** [comment]
Well, you copied the snippet, but forgot to change the values :wink: 

You need to change the colors for `ctermbg` and `ctermfg` groups if you're using Vim in terminal mode, otherwise `guibg` and `guifg` if running Vim in GUI mode. The color values for the GUI mode are simple HEX values, the color for the terminal mode are the 0-16 of the used terminal color palette.

For example, if you'd like to use `nord9` as background color for the matching brackets use change the snippet to

```vim
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight MatchParen ctermbg=4 ctermfg=0 guibg=#81A1C1 guifg=#2E3440
augroup END
colorscheme nord
```

**Comment by cryptomaniac512** [comment]
Wow, cool! Thanks a lot!

**Comment by arcticicestudio** [comment]
Your're welcome. Glad to see it worked :smile:

**Comment by dylnmc** [comment]
May I add to this convo? I feel as though the matching bracket is really confusing, as I do not use a blinking cursor.

eg, I have this in my vimrc

```vim
augroup nord
    autocmd ColorScheme * highlight MatchParen ctermbg=0 ctermfg=3
autogroup end
```

It's not the best solution (see the screenshot below), but it is better than having the same colors (very confusing for me).

If you could invest a few minutes and try and think of an alternative (maybe another user-defined boolean that allows the colors to be set to something more different), that would be amazeballs. If you don't have time/don't want to, I totally understand, as well, and will just keep my little vimrc change.

Thanks,
dylnmc

---

screenshot:

![tmp](https://user-images.githubusercontent.com/7635158/32983613-5ad14c4e-cc65-11e7-89bc-863f90575bf6.png)

**Comment by arcticicestudio** [comment]
Another theme configuration would a solution, but I've currently no design idea to solve this.
Only using the `bold` attribute for the foreground is barely noticeable and (sadly) the `bold` and `italic` attributes are still not supported by every shell/terminal. The same goes for another background color like `nord2`/`nord1` regarding the visibility.

I think users should just use the awesome Vim feature to override groups, thanks to the scoping it won't even affect other themes/plugins.

@dylnmc By the way, if you'd like to apply the modification you've posted above to Nord you should change the snippet to

```vim
augroup nord
    autocmd ColorScheme nord highlight MatchParen ctermbg=0 ctermfg=3
autogroup end
```

The `*` character causes this auto command group to be applied to every theme.

**Comment by dylnmc** [comment]
Are you implying that I use other colorschemes? 😏

Thanks .. fixed 🐈

**Comment by arcticicestudio** [comment]
Of course not! :stuck_out_tongue: 

But I think there's not reason to not use this feature to prevent any side effects.

**Comment by arcticicestudio** [comment]
@cryptomaniac512 @dylnmc You might like to subscribe to #75 and #78 which improves the highlighting for matching elements. The @vincentzhezhang came up with a nice idea while comparing it to the Gruvbox color scheme. I've posted some feedback in the PR and maybe you'd like to test and review the changes :smile:

**Comment by arcticicestudio** [comment]
> Duplicate of #75
