### ISSUE TITLE
Lightline theme screenshot doesn't reflect the theme

### ISSUE THREAD

**Issue by lokesh-krishna** [arcticicestudio/nord-vim#74]
I'm using the lightline theme and its appearance is different from the one shown in the screenshot. The screenshot shows triangles at the end of each section (?) whereas the theme, as it is installed now, only uses straight lines for its edges.

Here is what I'm talking about:

**Screenshot**

![scrot-plugin-support-ui-lightline](https://user-images.githubusercontent.com/20235646/32987814-5c03a89e-cd1b-11e7-9483-706482f21adb.png)

**Theme**

![screenshot from 2017-11-19 11-14-03](https://user-images.githubusercontent.com/20235646/32987815-6f66503a-cd1b-11e7-8a93-44e172bed258.png)

Is this what the theme looks like presently or is something wrong on my end?

**Comment by arcticicestudio** [comment]
The theme only configures the colors which will be used by the plugin to style the different components. The alignment, the shown content and layout must be set in the plugin configuration. Make sure to read the lightline [introduction][intro] to get to know the features and plugin configurations.

The screenshot is a mainly a preview for the colors, but I have to agree that it can be a bit confusing for new users so I'll add another screenshot using the default/vanilla lightline configurations.

Anyway, if you'd like to get the same layout and design as seen on the screenshot you can check out my Vim configuration in my [dotfile repository][dots]

[intro]: https://github.com/itchyny/lightline.vim#introduction
[dots]: https://github.com/arcticicestudio/igloo/blob/develop/snowblocks/vim/vimrc#L46-L105

**Comment by lokesh-krishna** [comment]
Thanks for pointing me to igloo! It's amazing!

**Comment by shaunsingh** [comment]
Hi. Sorry to bump such an old issue. the link to your dot files isn't working anymore, is there someplace else I can find them? I love the look of your status line

**Comment by lokesh-krishna** [comment]
The dotfiles repo is still around, it's just been restructured. Here is what you're looking for: [vimrc](https://github.com/arcticicestudio/igloo/blob/master/snowblocks/vim/vimrc).

**Comment by shaunsingh** [comment]
Thank you!
