### ISSUE TITLE
Denite with nord-vim makes some words disappearing

### ISSUE THREAD

**Issue by delphinus** [arcticicestudio/nord-vim#79]
With nord-vim & [denite.nvim][], it cannot show searching words.

But I don't know this matter is derived from Denite itself, or Nord colorscheme...

[denite.nvim]: https://github.com/Shougo/denite.nvim

### reproducing

1. Set iTerm2 colorscheme to Nord.

2. clone plugins

    ```sh
    mkdir /tmp/test
    cd /tmp/test
    git clone https://github.com/arcticicestudio/nord-vim
    git clone https://github.com/Shougo/denite.nvim
    ```

3. make minimal vimrc & launch Vim

    ```vim
    set runtimepath+=/tmp/test/denite.nvim,/tmp/test/nord-vim
    colorscheme nord
    ```

    ```sh
    vim -N -u vimrc -i NONE
    ```

4. launch denite & search some words

    ```vim
    :Denite file

    " and type some word to search
    vim
    ```

  <img width="479" alt="2017-12-02 0 14 40" src="https://user-images.githubusercontent.com/1239245/33489009-f21b6b08-d6f5-11e7-9dd3-ac07fce9ce29.png">

  The highlighted word `vim` disappeared only at top line.  (and strange a bit at the second line `nord-vim`)

### case: solarized

But with other colorschemes such as solarized, this does not occur.

1. Set iTerm2 colorscheme to Solarized Dark.

2. clone plugins

    ```sh
    mkdir /tmp/test
    cd /tmp/test
    git clone https://github.com/altercation/vim-colors-solarized
    git clone https://github.com/Shougo/denite.nvim
    ```

3. make minimal vimrc & launch Vim

    ```vim
    set runtimepath+=/tmp/test/denite.nvim,/tmp/test/vim-colors-solarized
    colorscheme solarized
    ```

    ```sh
    vim -N -u vimrc -i NONE
    ```

4. launch denite & search some words

    ```vim
    :Denite file

    " and type some word to search
    vim
    ```

  <img width="479" alt="2017-12-04 21 00 01" src="https://user-images.githubusercontent.com/1239245/33551919-61d4d44c-d936-11e7-8dc7-501e9b800622.png">

**Comment by arcticicestudio** [comment]
This can be related to `WildMenu` or `Search` groups which are [used by the plugin][ref-code]. I'll see if it'll be fixed when #64 is done which will change the `WildMenu` group.

[ref-code]: https://github.com/Shougo/denite.nvim/blob/master/autoload/denite/init.vim#L92-L97

**Comment by delphinus** [comment]
Thx for quick response, and I can understand the reason!  I'm waiting for #64 to be solved, and I use setting below for a while.

```vim
set runtimepath+=/tmp/test/denite.nvim,/tmp/test/nord-vim
colorscheme nord
call denite#custom#option('default', 'highlight_matched_char', 'PreProc')
```

**Comment by arcticicestudio** [comment]
@delphinus #64 has been closed. Can you please check if the problem still exists or if it has been fixed?

**Comment by delphinus** [comment]
Still reproducing...  Sorry, I misunderstood the reason.  That is why denite.nvim is using `CursorLine` for selecting candidates, and `Search` for input words.  Highlights in nord makes words disappear with `Search` on `CursorLine`.

But without denite, Vim shows searhing words validly even if with `set cursorline` in nord.  So it seems that the cause is more than on denite itself.

**Comment by delphinus** [comment]
I think this is spec in Denite, and I solved this by settings.  So close this.  Thx.
