### ISSUE TITLE
Wrong svg banner for iTerm in README file

### ISSUE THREAD

**Issue by shvetsovdm** [arcticicestudio/nord-vim#8]
iTerm banner https://cdn.rawgit.com/arcticicestudio/nord/develop/src/assets/nord-iterm2-banner.svg looks the same as GNOME svg banner.

**Comment by arcticicestudio** [comment]
Thanks for your report 👍 
Due to the fact that the banner is linked from the main Nord repository I've moved this issue to [`nord #9`](https://github.com/arcticicestudio/nord/issues/9).
