### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by urbainvaes** [arcticicestudio/nord-vim#83]
Hi!

First, thank you very much for your good work on this colorscheme, I love it. I thought I'd share two suggestions I have:

- Is it possible to assign to the gutter a colour different from the buffer background colour? In the current version, it is sometimes difficult, when using vim without numbers or relative numbers, to know whether the space at the beginning of the line is part of the gutter or of the file.

- I always get confused when my cursor is on a delimiter, because the corresponding delimiter is highlighted in a very bright colour. I would suggest using a darker colour for the matched delimiter.

Feel free to ignore any suggestion you don't like.

**Comment by arcticicestudio** [comment]
Thanks for your contribution :+1: 

I think you are referring to the `FoldColumn`.

It is possible to customize all theme groups to fit your personal preferences via a `augroup`. Add it to your `~/.vimrc` to override the [default Gutter styles][ref-gutter] only for the Nord color theme.

For example this snippet changes the background color of the `FoldColumn` group from `nord0` to `nord1`:

```vim
augroup nord-overrides
  autocmd!
  autocmd ColorScheme nord highlight FoldColumn guibg=#3B4252 ctermbg=0
augroup END
```

![gh-83-scrot-preview-foldcolumn-after](https://user-images.githubusercontent.com/7836623/33794241-21e02f5e-dcc8-11e7-996d-286227f8bde9.png)

If you'd like to hide the column completely you can set the width of the `foldcolumn` option to `0` in your `~/.vimrc`:

```vim
foldcolumn=0
```

Maybe your second improvement suggestion is related to #75?

[ref-gutter]: https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L170#L175

**Comment by urbainvaes** [comment]
Hi!

Thank you very much for your detailed repsonse. 

The code snippet you wrote does change the colour of the foldcolumn, but there is another column in the "gutter" that is not part of the foldcolumn: it contains marks when using vim-signify, +/-/~ when using vim git-gutter, warning and error signs when using syntastic, etc... 

I suppose this column corresponds to a different highlight group, and that a simple adaptation of what you wrote would change its colour too. I haven't found what it is yet, but I'll look into it.

And yes, my second suggestion is indeed covered in #75.

Best, Urbain

**Comment by arcticicestudio** [comment]
Since these groups are all independently of each other and each group defines it own style you'll need to customize them all, but I think it shouldn't be a problem by just using a simple autocommand group like described above.

Also almost every plugin that adds content to the sign column provides a way to customize the style e.g. read the [chapter about the sign column of the GitGutter plugin]:

> By default vim-gitgutter will make the sign column look like the line number column.
> 
>To customise your sign column's background color, first tell vim-gitgutter to leave it alone:
> 
> ```vim
> let g:gitgutter_override_sign_column_highlight = 0
> ```
> And then either update your colorscheme's SignColumn highlight group or set it in your vimrc:
> 
> ```vim
> highlight SignColumn ctermbg=whatever    " terminal Vim
> highlight SignColumn guibg=whatever      " gVim/MacVim
> ```

[ref]: https://github.com/airblade/vim-gitgutter#sign-column

**Comment by urbainvaes** [comment]
Hi!

Thank you very much for the detailed answer. I like to keep my .vimrc short, so I will probably just turn on `number` or `relativenumber` for now, but it's useful to know an alternative.

Best, Urbain
