### ISSUE TITLE
Unable to render italics in Markdown

### ISSUE THREAD

**Issue by lokesh-krishna** [arcticicestudio/nord-vim#84]
I admit that I am not sure if this is an issue with my terminal (rxvt-unicode now and Gnome Terminal earlier) or the theme but while I am able to see bold as well as bold italic, italic never renders, appearing instead as regular text.

I know the terminals are capable of rendering italics as I checked that by running `echo -e "\e[3mfoo\e[23m"` and the text did render in italics. 

Could you offer some insight into the matter? Please let me know if you require any information.

**Comment by arcticicestudio** [comment]
Does it work if you enable the [theme configuration for italic comments][tc-ic]?
Also is it reproducible with other color schemes?

I've shortly checked the theme and noted that the `markdownItalic` and `markdownBold` are indeed not set. Can you try to add the following to the theme and check if it fixes italics?

```vim
hi! link markdownItalic Italic
hi! link markdownBold Bold
```

[tc-ic]: https://github.com/arcticicestudio/nord-vim#italic-comments

**Comment by lokesh-krishna** [comment]
I tried enabling italic comments and that too doesn't work. 

I've never used a theme before that actually rendered markdown in italics. The base16 ones I used simply used colors and one of the things I really appreciate this theme is that it actually formats instead of coloring.

I tried adding what you suggested but that too didn't fix italics :(

**Comment by lokesh-krishna** [comment]
Could you please consider highlighting italics, bold and bold italics using colors instead of formatting? 

Maybe offer formatting as an option the way that you do with comments. I would love to see it formatted but seeing how you warn about italics for comments with respect to terminal support, what do you think of offering colored highlighting as the default when it comes to Markdown?

**Comment by lokesh-krishna** [comment]
Tested it with no color scheme at all and italics works there.

**Comment by dylnmc** [comment]
This theme uses italics. Read the README to see how to enable italics.

It seems like you're having another problem, or you're not following the README, but I can't tell because you're just asking to support italics (it does), but you're not clearly stating the exact problem.

**Comment by lokesh-krishna** [comment]
> This theme uses italics if you enable italics via a global flag before using `colorscheme nord`.

Thanks a lot for this. I tested this earlier by adding this line after setting the color scheme and that didn't have any effect. Adding it before does show comments in italics. It also fixes italics in Markdown files. 

@arcticicestudio So yes, that flag does fix things but I would like to have italics only for italics in Markdown files, not for comments. Is there anything I can do to make things that way?

**Comment by dylnmc** [comment]
seems you're right. Thanks for clearly stating the problem.

@arcticicestudio ... in *markdown* files, `*hello*` is hl group `markDownItalic` =[linked to]=> `htmlItalic` =[linked to]=> `Italic`.

* `verbose hi Italic` yields:

```
Italic         xxx cterm=italic gui=italic
	Last set from ~/vimfiles/plugged/nord-vim/colors/nord.vim
```

**Comment by arcticicestudio** [comment]
I've been thinking about adding a configuration to allow users to enable italics.The implementation can be made using a variable which gets initialized with `italic` when the configuration is enabled, otherwise the variable will be a empty string.

**Comment by lokesh-krishna** [comment]
Is there anything one can do presently to have italics in markdown files but not for comments?

**Comment by dylnmc** [comment]
```vim
augroup MyNordChanges
    autocmd!
    autocmd ColorScheme nord highlight Comment cterm=NONE gui=NONE
    autocmd ColorScheme nord highlight Italic cterm=italic gui=italic
augroup end
```

**Comment by lokesh-krishna** [comment]
Thanks a lot! Correct me if I'm wrong but just adding this much, before declaring the color scheme seems to do exactly what I want:  

`autocmd ColorScheme nord highlight Italic cterm=italic gui=italic`

I no longer have `let g:nord_italic_comments = 1` though.

Anyway you could make this the default behaviour of the color scheme, with a PR? Provided @arcticicestudio approves.

**Comment by dylnmc** [comment]
Your autocmd does do what you desire. I was just more explicit and handled some edge cases.

---

You wouldn't want to make italics available by _default_, but I think, arcticice is considering making italics easier to deal with when one might want italics (for example in markdown, with comments, etc). A lot of terminals (and some fonts) do not support italics.

I might have a go at a small refactor and submit a PR if and see what @arcticicestudio thinks. But I also know how tidy and organi{s,z}ed arcticice is, so I feel like I might just be trampling on toes. Nonetheless, I agree that italic support should be improved.

**Comment by arcticicestudio** [comment]
I've submitted #89 which adds a new option to explicitly enable italics. The `nord_italic_comments` option now requires the new option to enabled in order to take effect. I'll add the missing groups for the Markdown syntax to fix the problem with italic syntax styles.
