### ISSUE TITLE
Comments are hard to read

### ISSUE THREAD

**Issue by markand** [arcticicestudio/nord-vim#86]
Hello,

I'm using both nord for XResources and vim, and to me, it looks very hard to read especially when I'm not directly aligned to the screen. For example, looking at the top of my screen.

I wonder if I have a color that is wrong or if it's really designed like this:

![2017-12-18-102934_689x176_scrot](https://user-images.githubusercontent.com/11919008/34099280-607b801a-e3df-11e7-92cd-51c759f1ec5b.png)

**Comment by arcticicestudio** [comment]
You can customize the contrast of the comment color via the [comment contrast][cc] theme configuration.

[cc]: https://github.com/arcticicestudio/nord-vim#comment-contrast

**Comment by markand** [comment]
Hello,

I didn't know there was options for the theme. Thanks and sorry to didn't see it earlier :)
