### ISSUE TITLE
Configuration for italics

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord-vim#88]
The [configuration to enable italic comments][cfg-it_com] is like the name suggests limited to comments only, but there are other use cases like the [italic style in Markdown][gh-84].

A new theme configuration should be added to explicitly enable italics. It should be enabled by default when running in *gui* mode and should be disabled by default in *term*.

The reason for this standard behavior is the fact that there are still shells and terminals which are not able to handle italics. Enabling italics for terminals by default would cause unpredictable bugs and graphical glitches.

The new configuration should be named `nord_italic`.

[cfg-it_com]: https://github.com/arcticicestudio/nord-vim#italic-comments
[gh-84]: https://github.com/arcticicestudio/nord-vim/issues/84

**Comment by lokesh-krishna** [comment]
How will italics be highlighted in terminals by default then? And will this be consistent with the highlighting for bold and bold italics which are formatted as bold and bold italics presently and alsoenabled by default?

**Comment by arcticicestudio** [comment]
*Italic* is a attribute for the font and is not related to highlighting which is mainly supposed to apply colors.

Example: The keyword `class` is highlighted with `nord9`. If the `italic` attribute is also applied it will only take effect if `g:nord_italic` has been set to `1`, otherwise `class` will only be colorized but without an additional font attribute.

The `bold` attribute is not known to cause problems and is currently used without any further configurations (there are plans to add a `g:nord_bold` configuration to allow user to also explicitly disable bold styled text). When an syntax element is styled with both `italic` and `bold`, but `g:nord_italic` is not enabled only the `bold` attribute will be applied.

The decision to disable italics by default is only related to the fact that there are still some terminals (mostly old or used for legacy reasons) that are not able to handle italics, even if almost 95% of all modern and commonly used terminals are supporting it. If you're using a common modern terminal like a VTE-based one (e.g. [Tilix][ti], [GNOME Terminal][gt] and variants, [Termite][tm], etc.), [rxvt-unicode][rx], [Alacritty][ac] or any NodeJS/Electron based App that uses web technologies ([xterm.js][xt) e.g. [Hyper][h], [Upterm][ut] or [Terminus][tm] you won't have any problems with italics.

[gist]: https://gist.github.com/XVilka/8346728
[xt]: https://www.npmjs.com/package/xterm
[h]: https://hyper.is
[ut]: https://github.com/railsware/upterm
[tm]: https://github.com/Eugeny/terminus
[ac]: https://github.com/jwilm/alacritty
[ti]: https://gnunn1.github.io/tilix-web/
[gt]: https://help.gnome.org/users/gnome-terminal/stable/
[tm]: https://wiki.archlinux.org/index.php/termite
[rx]: https://wiki.archlinux.org/index.php/rxvt-unicode

**Comment by lokesh-krishna** [comment]
Thank you so much for the thorough reply :) Really appreciate it.

> The keyword class is highlighted with nord9. If the italic attribute is also applied it will only take effect if g:nord_italic has been set to 1, otherwise class will only be colorized but in a normal font style.

This is what I wanted to know with respect to italics. What color will it be highlighted by as by default, `g:nord_italic` is set to `0` (not been set to `1`)? Since bold in markdown will be formatted as bold by default, wouldn't it be weird to have italics highlighted with a color and bold formatted?

I do understand the decision to disable italics by default though, thanks to your explanation. Just curious about how you'll handle the default situation.

**Comment by arcticicestudio** [comment]
In the case of #84 for the Markdown syntax italic styled text will use the color of the group that is assigned. There will be no additional styles or kind of "alternative styles" when italics are disabled. So e.g. italic formatted inline code will use the color of the Markdown inline code group while normal text (paragraphs) will be colored with the default text color. It is still easy to recognize italic formatted Markdown text even if `nord_italic` is not enabled because the `*` / `_` identifier characters are highlighted as keywords (`nord9`).

![gh-88-scrot-md-style-no-italic](https://user-images.githubusercontent.com/7836623/34446033-4d5ac444-ecd8-11e7-9664-771aaa7ad62e.png)

**Comment by lokesh-krishna** [comment]
Thank you so much for implementing it so elegantly!
