### ISSUE TITLE
Add highlighting for vimwiki

### ISSUE THREAD

**Issue by odd-is-yes** [arcticicestudio/nord-vim#98]
considering nord plays so well with stuff light lightline I'm suprised you haven't added highlighting so that the headers and todo lists look good on [vimwiki](https://github.com/vimwiki/vimwiki) considering it's such a popular plugin.

**Comment by arcticicestudio** [comment]
Thanks for the great detailed feature request :+1: 

I'm always happy for any help to get a new port project started.

Please note that my current life situation doesn't allow me to spend as much time on my projects as before [like announced on Twitter][t] so I've added this port project to the [Backlog Icebox][ib] for the time being. It might take some time to test things out, but I'll try to reserve some free time on the weekends.

[ib]: https://github.com/arcticicestudio/nord-vim/projects/1#column-493799
[t]: https://twitter.com/arcticicestudio/status/954067233067675650

**Comment by smesko85** [comment]
I don't use vimwiki as much, but this is looking kinda ok for me:
```vim
" Vimwiki
" > vimwiki/vimwiki
call s:hi("VimwikiLink", s:nord9_gui, "", s:nord9_term, "", "underline", "")
if !exists("g:vimwiki_hl_headers") || g:vimwiki_hl_headers == 0
  for s:i in range(1,6)
    call s:hi("VimwikiHeader".s:i, s:nord7_gui, "", s:nord7_term, "", "bold", "")
  endfor
else
  let s:vimwiki_hcolor_guifg = [s:nord7_gui, s:nord8_gui, s:nord9_gui, s:nord10_gui, s:nord15_gui, s:nord14_gui]
  let s:vimwiki_hcolor_ctermfg = [s:nord7_term, s:nord8_term, s:nord9_term, s:nord10_term, s:nord15_term, s:nord14_term]
  for s:i in range(1,6)
    call s:hi("VimwikiHeader".s:i, s:vimwiki_hcolor_guifg[s:i-1] , "", s:vimwiki_hcolor_ctermfg[s:i-1], "", "bold", "")
  endfor
endif

call s:hi("VimwikiList", s:nord15_gui, "", s:nord15_term, "", "", "")
```
@odd-is-yes can you try it, and see if anything is missing and/or looking bad?
We could tweak it and submit PR afterwards.
